/**
 * Dashtock Uygulama Mağazası — katalog (ikas apps benzeri)
 * panelRoute: UserDashboard activePanel
 * externalUrl: harici mağaza sayfası (opsiyonel)
 */
const CATEGORIES = [
    { id: "magaza", name: "Mağaza & Satış", order: 1 },
    { id: "pazaryeri", name: "Pazaryeri", order: 2 },
    { id: "odeme", name: "Ödeme", order: 3 },
    { id: "pazarlama", name: "Pazarlama", order: 4 },
    { id: "kargo", name: "Kargo & Lojistik", order: 5 },
    { id: "finans", name: "Finans & Fatura", order: 6 },
    { id: "analitik", name: "Analitik & Rapor", order: 7 },
    { id: "ai", name: "Yapay Zeka", order: 8 },
];

const APPS = [
    {
        appKey: "web-store",
        name: "Web Sitem",
        shortDescription: "Kendi domain ve PayTR ile online mağaza. Ürün vitrini, sepet ve ödeme.",
        description: "İkas benzeri e-ticaret mağazanızı dakikalar içinde kurun. Kendi PayTR bilgilerinizle ödeme alın, ürünlerinizi Ürün Merkezi ile senkronize edin.",
        categoryId: "magaza",
        icon: "store",
        color: "#4ecdc4",
        panelRoute: "store-hub",
        featureId: "own_storefront",
        minPlan: "basic",
        isCore: true,
        sortOrder: 1,
    },
    {
        appKey: "trendyol-channel",
        name: "Trendyol Entegrasyonu",
        shortDescription: "Sipariş, stok ve ürün senkronizasyonu.",
        categoryId: "pazaryeri",
        icon: "trendyol",
        color: "#F27A1A",
        panelRoute: "integration",
        featureId: "products",
        minPlan: "trial",
        isCore: true,
        sortOrder: 10,
    },
    {
        appKey: "hepsiburada-channel",
        name: "Hepsiburada Entegrasyonu",
        shortDescription: "HB katalog, sipariş ve stok yönetimi.",
        categoryId: "pazaryeri",
        icon: "hepsiburada",
        color: "#FF6000",
        panelRoute: "integration",
        featureId: "products",
        minPlan: "trial",
        isCore: true,
        sortOrder: 11,
    },
    {
        appKey: "n11-channel",
        name: "N11 Entegrasyonu",
        shortDescription: "N11 API bağlantısı ve sipariş akışı.",
        categoryId: "pazaryeri",
        icon: "n11",
        color: "#7B2D8E",
        panelRoute: "integration",
        featureId: "products",
        minPlan: "basic",
        sortOrder: 12,
    },
    {
        appKey: "ciceksepeti-channel",
        name: "Çiçeksepeti Entegrasyonu",
        shortDescription: "Çiçeksepeti sipariş ve ürün senkronu.",
        categoryId: "pazaryeri",
        icon: "ciceksepeti",
        color: "#E91E63",
        panelRoute: "integration",
        featureId: "products",
        minPlan: "pro",
        sortOrder: 13,
    },
    {
        appKey: "amazon-channel",
        name: "Amazon Entegrasyonu",
        shortDescription: "Amazon SP-API sipariş ve envanter.",
        categoryId: "pazaryeri",
        icon: "amazon",
        color: "#FF9900",
        panelRoute: "integration",
        featureId: "products",
        minPlan: "pro",
        sortOrder: 14,
    },
    {
        appKey: "store-paytr",
        name: "Mağaza PayTR Ödemesi",
        shortDescription: "Müşterileriniz sizin PayTR hesabınıza öder.",
        categoryId: "odeme",
        icon: "paytr",
        color: "#00A651",
        panelRoute: "store-hub",
        panelQuery: { tab: "payments" },
        featureId: "own_storefront",
        minPlan: "basic",
        sortOrder: 20,
    },
    {
        appKey: "product-center",
        name: "Ürün Yönetim Merkezi",
        shortDescription: "Merkezi ürün, stok ve dağıtım.",
        categoryId: "magaza",
        icon: "products",
        color: "#8b5cf6",
        panelRoute: "pm-center",
        featureId: "products",
        minPlan: "trial",
        isCore: true,
        sortOrder: 2,
    },
    {
        appKey: "category-center",
        name: "Kategori Merkezi",
        shortDescription: "Master kategori eşleştirme tablosu.",
        categoryId: "magaza",
        icon: "category",
        color: "#ec4899",
        panelRoute: "category-center",
        featureId: "category_center",
        minPlan: "basic",
        sortOrder: 3,
    },
    {
        appKey: "e-invoice",
        name: "E-Fatura & Faturalama",
        shortDescription: "QNB e-Fatura, otomatik fatura kesimi.",
        categoryId: "finans",
        icon: "invoice",
        color: "#3b82f6",
        panelRoute: "billing",
        featureId: "e_invoice",
        minPlan: "pro",
        sortOrder: 30,
    },
    {
        appKey: "marketing-email",
        name: "E-Posta & SMS Pazarlama",
        shortDescription: "Kampanya, otomasyon ve segmentler.",
        categoryId: "pazarlama",
        icon: "email",
        color: "#a855f7",
        panelRoute: "marketing-email",
        featureId: "store_marketing",
        minPlan: "pro",
        comingSoon: true,
        sortOrder: 40,
    },
    {
        appKey: "marketing-automation",
        name: "Pazarlama Otomasyonu",
        shortDescription: "Tetikleyici bazlı otomatik akışlar.",
        categoryId: "pazarlama",
        icon: "automation",
        color: "#c084fc",
        panelRoute: "marketing-automation",
        featureId: "store_marketing",
        minPlan: "pro",
        comingSoon: true,
        sortOrder: 41,
    },
    {
        appKey: "marketing-segments",
        name: "Müşteri Segmentleri",
        shortDescription: "Canlı segmentler ve hedef kitle.",
        categoryId: "pazarlama",
        icon: "segments",
        color: "#e879f9",
        panelRoute: "marketing-segments",
        featureId: "store_marketing",
        minPlan: "pro",
        comingSoon: true,
        sortOrder: 42,
    },
    {
        appKey: "marketing-popup",
        name: "Popup & Dönüşüm",
        shortDescription: "Çıkış intent, indirim popup.",
        categoryId: "pazarlama",
        icon: "popup",
        color: "#f472b6",
        panelRoute: "marketing-popup",
        featureId: "store_marketing",
        minPlan: "basic",
        comingSoon: true,
        sortOrder: 43,
    },
    {
        appKey: "discounts",
        name: "İndirimler & Kuponlar",
        shortDescription: "Kupon kodu ve kampanya yönetimi.",
        categoryId: "pazarlama",
        icon: "discount",
        color: "#f59e0b",
        panelRoute: "marketing-discounts",
        featureId: "store_marketing",
        minPlan: "pro",
        comingSoon: true,
        sortOrder: 44,
    },
    {
        appKey: "dashtock-ai",
        name: "Dashtock AI",
        shortDescription: "AI asistan, öneriler ve operasyon desteği.",
        categoryId: "ai",
        icon: "brain",
        color: "#4ecdc4",
        panelRoute: "lysia-brain",
        featureId: "ai_assistant",
        minPlan: "pro",
        sortOrder: 50,
    },
    {
        appKey: "radar-pro",
        name: "Fırsat Radarı PRO",
        shortDescription: "Pazaryeri fırsat ve rakip analizi.",
        categoryId: "ai",
        icon: "radar",
        color: "#22c55e",
        panelRoute: "radar-pro",
        featureId: "ai_radar",
        minPlan: "pro",
        sortOrder: 51,
    },
    {
        appKey: "roketfy",
        name: "Roketfy",
        shortDescription: "Liste optimizasyonu ve pazar araştırması.",
        categoryId: "ai",
        icon: "rocket",
        color: "#f97316",
        panelRoute: "roketfy",
        featureId: "roketfy",
        minPlan: "pro",
        sortOrder: 52,
    },
    {
        appKey: "profit-analytics",
        name: "Gelişmiş Analitik",
        shortDescription: "Kâr/zarar ve kanal raporları.",
        categoryId: "analitik",
        icon: "chart",
        color: "#eab308",
        panelRoute: "advanced-analytics",
        featureId: "profit_analytics",
        minPlan: "pro",
        sortOrder: 60,
    },
    {
        appKey: "orders-hub",
        name: "Sipariş Merkezi",
        shortDescription: "Tüm kanallardan sipariş yönetimi.",
        categoryId: "magaza",
        icon: "orders",
        color: "#06b6d4",
        panelRoute: "orders",
        featureId: "orders",
        minPlan: "trial",
        isCore: true,
        sortOrder: 4,
    },
];

module.exports = { CATEGORIES, APPS };
