import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

/* 
   DL SZL
    */
const translations = {
    tr: {
        // Sidebar
        "sidebar.home": "Ana Sayfa",
        "sidebar.marketplace": "Pazaryeri",
        "sidebar.integrations": "Entegrasyonlar",
        "sidebar.orders": "Sipariş Yönetimi",
        "sidebar.returns": "İade Yönetimi",
        "sidebar.inventory": "Stok Yönetimi",
        "sidebar.shipping": "Kargo Yönetimi",
        "sidebar.finance": "Finans Yönetimi",
        "sidebar.productMgmt": "Ürün Yönetimi",
        "sidebar.productCenter": "Ürün Merkezi",
        "sidebar.productUpload": "Ürün Yükle & Dağıt",
        "sidebar.categoryCenter": "Kategori Merkezi",

        "sidebar.analytics": "Analiz & AI",
        "sidebar.advancedAnalytics": "Gelişmiş Analiz",
        "sidebar.aiAssistant": "AI Asistan",
        "sidebar.roketfy": "Dashtock Radar",
        "sidebar.radarPro": "AI Fırsat Radarı",
        "sidebar.management": "Yönetim",
        "sidebar.userMgmt": "Kullanıcı Yönetimi",
        "sidebar.billing": "Faturalandırma",
        "sidebar.support": "Destek Talebi",
        "sidebar.settings": "Ayarlar",
        "sidebar.adminPanel": "Admin Paneli",
        "sidebar.logout": "Oturumu Kapat",
        "sidebar.logoutConfirm": "Oturumu kapatmak istediğinize emin misiniz?",

        // Dashboard
        "dashboard.greeting.morning": "Günaydın",
        "dashboard.greeting.afternoon": "İyi günler",
        "dashboard.greeting.evening": "İyi akşamlar",
        "dashboard.greeting.night": "İyi geceler",
        "dashboard.totalOrders": "Toplam Sipariş",
        "dashboard.totalRevenue": "Toplam Ciro",
        "dashboard.productCount": "Ürün Sayısı",
        "dashboard.lowStock": "Düşük Stok",
        "dashboard.weeklyOrders": "7 Günlük Sipariş",
        "dashboard.delivered": "Teslim Edilen",
        "dashboard.new": "yeni",
        "dashboard.processing": "işlemde",
        "dashboard.shipping": "Kargoda",
        "dashboard.cancel": "İptal",
        "dashboard.return": "İade",
        "dashboard.active": "Aktif",
        "dashboard.passive": "Pasif",
        "dashboard.outOfStock": "Stok tükendi",
        "dashboard.avgBasket": "Ort. sepet",
        "dashboard.activeChannels": "Aktif kanal",
        "dashboard.errors": "Hata",
        "dashboard.pendingSync": "Bekleyen senkronizasyon",
        "dashboard.stockMismatch": "Stok farkı",
        "dashboard.lastUpdate": "Son Güncelleme",
        "dashboard.recentOrders": "Son Siparişler",
        "dashboard.viewAll": "Tümü",
        "dashboard.noOrders": "Henüz sipariş yok",
        "dashboard.alerts": "Uyarılar ve bildirimler",
        "dashboard.noAlerts": "Aktif uyarı yok",
        "dashboard.channelRevenue": "Kanal bazlı gelir",
        "dashboard.quickActions": "Hızlı işlemler",
        "dashboard.operationLogs": "Operasyon logları",
        "dashboard.noLogs": "Henüz işlem kaydı yok",

        // Settings
        "settings.title": "Ayarlar",
        "settings.subtitle": "Uygulama tercihlerİşinizi ve hesap ayarlarnz yönetin",
        "settings.appearance": "Grnm",
        "settings.theme": "Tema",
        "settings.themeDesc": "Arayz temasn sein",
        "settings.dark": "Koyu",
        "settings.light": "Ak",
        "settings.system": "Sistem",
        "settings.language": "Dil",
        "settings.languageDesc": "Arayz dilini sein",
        "settings.turkish": "Trke",
        "settings.english": "English",
        "settings.notifications": "Bildirimler",
        "settings.notifDesc": "Bildirim tercihlerİşinizi yönetin",
        "settings.orderNotif": "Sipariş Bildirimleri",
        "settings.orderNotifDesc": "Yeni sipariş geldiinde bildirim al",
        "settings.stockNotif": "Stok Bildirimleri",
        "settings.stockNotifDesc": "Dk stok uyarlaürün al",
        "settings.soundNotif": "Ses Bildirimleri",
        "settings.soundNotifDesc": "Bildirim geldiinde ses al",
        "settings.emailNotif": "E-posta Bildirimleri",
        "settings.emailNotifDesc": "nemli güncellemeleri e-posta ile al",
        "settings.account": "Hesap",
        "settings.accountDesc": "Hesap bilgilerİşinizi yönetin",
        "settings.name": "Ad Soyad",
        "settings.email": "E-posta",
        "settings.phone": "Telefon",
        "settings.company": "irket",
        "settings.save": "Kaydet",
        "settings.saved": "Kaydedildi!",
        "settings.saving": "Kaydediliyor...",
        "settings.security": "Gvenlik",
        "settings.securityDesc": "şifre ve gvenlik ayarlarnz yönetin",
        "settings.currentPassword": "Mevcut şifre",
        "settings.newPassword": "Yeni şifre",
        "settings.confirmPassword": "şifre Tekrar",
        "settings.changePassword": "şifreyi Değiştir",
        "settings.dangerZone": "Tehlikeli Blge",
        "settings.deleteAccount": "Hesab Sil",
        "settings.deleteAccountDesc": "Bu ilem geri alnamaz. Tüm verileriniz silinecektir.",
        "settings.subscription": "Abonelik",
        "settings.plan": "Plan",
        "settings.planFree": "Ücretsiz",
        "settings.planBasic": "Temel",
        "settings.planPro": "Profesyonel",
        "settings.planEnterprise": "Kurumsal",

        // Admin
        "admin.title": "Admin Paneli",
        "admin.subtitle": "Sistem yönetimi ve kullanc kontrol",
        "admin.users": "Kullanıcılar",
        "admin.system": "Sistem Durumu",
        "admin.logs": "Sistem Loglar",
        "admin.settings": "Sistem Ayarlar",
        "admin.totalUsers": "Toplam Kullanıcı",
        "admin.activeToday": "Bugn Aktif",
        "admin.totalIntegrations": "Toplam Entegrasyon",
        "admin.serverUptime": "Sunucu Uptime",
        "admin.search": "Kullanıcı ara...",
        "admin.allRoles": "Tüm Roller",
        "admin.role": "Rol",
        "admin.registered": "Kayıt Tarihi",
        "admin.actions": "lemler",
        "admin.edit": "Dzenle",
        "admin.delete": "Sil",
        "admin.impersonate": "Panele Gir",
        "admin.cpu": "CPU Kullanm",
        "admin.memory": "Bellek Kullanm",
        "admin.database": "Veritaban",
        "admin.connected": "Bal",
        "admin.disconnected": "Balant Yok",
        "admin.nodeVersion": "Node.js",
        "admin.platform": "Platform",
        "admin.hostname": "Sunucu Ad",
        "admin.noLogs": "Log kayd bulunamad",

        // Auth & 2FA
        "auth.login": "Giriş Yap",
        "auth.register": "Kayıt Ol",
        "auth.logout": "k Yap",
        "auth.email": "E-posta",
        "auth.password": "şifre",
        "auth.forgotPassword": "Şifremi Unuttum",
        "auth.rememberMe": "Beni Hatrla",
        "auth.noAccount": "Hesabınız yok mu?",
        "auth.hasAccount": "Zaten hesabınız var mı?",
        "auth.2fa.title": "ki Faktrl Doğrulama",
        "auth.2fa.subtitle": "E-posta adresinize gönderilen 6 haneli kodu girin",
        "auth.2fa.code": "Doğrulama Kodu",
        "auth.2fa.verify": "Doğrula",
        "auth.2fa.resend": "Kodu Tekrar Gönder",
        "auth.2fa.backupCode": "Yedek kod kullan",
        "auth.2fa.enable": "2FA Aktifletir",
        "auth.2fa.disable": "2FA Kapat",
        "auth.2fa.enabled": "ki faktrl dorulama aktif",
        "auth.2fa.disabled": "ki faktrl dorulama kapal",

        // Marketplace
        "marketplace.title": "Pazaryeri Entegrasyonlar",
        "marketplace.add": "Entegrasyon Ekle",
        "marketplace.test": "Balant Test Et",
        "marketplace.connected": "Bal",
        "marketplace.disconnected": "Balant Yok",
        "marketplace.credentials": "API Bilgileri",
        "marketplace.sync": "Senkronize Et",
        "marketplace.lastSync": "Son Senkronizasyon",

        // Products
        "products.title": "ürünler",
        "products.total": "Toplam rn",
        "products.active": "Aktif",
        "products.passive": "Pasif",
        "products.outOfStock": "Stok Tkendi",
        "products.search": "ürün ara...",
        "products.export": "Da Aktar",
        "products.import": "e Aktar",
        "products.create": "Yeni rn",
        "products.distribute": "Dat",
        "products.bulkActions": "Toplu lem",

        // Orders
        "orders.title": "Siparişler",
        "orders.total": "Toplam Sipariş",
        "orders.pending": "Bekleyen",
        "orders.shipped": "Kargoda",
        "orders.delivered": "Teslim Edildi",
        "orders.cancelled": "İptal",
        "orders.returned": "İade",

        // Finance
        "finance.title": "Finans",
        "finance.revenue": "Gelir",
        "finance.expense": "Gider",
        "finance.profit": "Kr",
        "finance.commission": "Komisyon",
        "finance.settlement": "Hesap Kesimi",

        // AI
        "ai.title": "AI Asistan",
        "ai.suggestions": "neriler",
        "ai.score": "AI Skoru",
        "ai.optimize": "Optimize Et",
        "ai.simulate": "Simlasyon",
        "ai.brain": "AI Beyin",
        "ai.chat": "AI Chat",

        // Common
        "common.loading": "Ykleniyor...",
        "common.error": "Hata oluştu",
        "common.retry": "Tekrar Dene",
        "common.cancel": "İptal",
        "common.confirm": "Onayla",
        "common.close": "Kapat",
        "common.yes": "Evet",
        "common.no": "Hayr",
        "common.save": "Kaydet",
        "common.delete": "Sil",
        "common.edit": "Dzenle",
        "common.search": "Ara...",
        "common.filter": "Filtrele",
        "common.export": "Da Aktar",
        "common.import": "e Aktar",
        "common.refresh": "Yenile",
        "common.back": "Geri",
        "common.next": "leri",
        "common.previous": "Önceki",
        "common.noData": "Veri bulunamad",
        "common.success": "lem başarılı",
        "common.total": "Toplam",

        // Dashboard Extended
        "dashboard.error": "Hata",
        "dashboard.lowStockAlert": "Düşük Stok",
        "dashboard.marketplaceStatus": "Pazaryeri Durumu",
        "dashboard.channel": "Kanal",
        "dashboard.status": "Durum",
        "dashboard.orders": "Sipariş",
        "dashboard.revenue": "Ciro",
        "dashboard.slow": "Yavaş",
        "dashboard.unknown": "Bilinmiyor",
        "dashboard.weeklyTrend": "7 günlük trend",
        "dashboard.productHealth": "Ürün ve stok sağlığı",
        "dashboard.totalProducts": "Toplam ürün",
        "dashboard.activeProducts": "Aktif ürün",
        "dashboard.stockMismatchCount": "Stok uyumsuzluğu",
        "dashboard.allSystemsNormal": "Tüm sistemler normal",
        "dashboard.noData": "Veri yok",
        "dashboard.orderManagement": "Sipariş Yönetimi",
        "dashboard.stockManagement": "Stok Yönetimi",
        "dashboard.productCenter": "Ürün Merkezi",
        "dashboard.integrations": "Entegrasyonlar",
        "dashboard.finance": "Finans",
        "dashboard.viewAllLogs": "Tümünü gör",
        "dashboard.showingOrders": "sipariş gösteriliyor",
        "dashboard.goToOrderManagement": "Sipariş yönetimine git",
        "dashboard.noCategoryOrders": "Bu kategoride sipariş bulunamadı",
        "dashboard.marketplaceDistribution": "Pazaryeri ürün dağılımı",
        "dashboard.synced": "Senkron",
        "dashboard.errorProducts": "Hata",
        "dashboard.all": "Tümü",
        "dashboard.newOrders": "Yeni",
        "dashboard.processingOrders": "İşlemde",
        "dashboard.shippingOrders": "Kargoda",
        "dashboard.deliveredOrders": "Teslim",
        "dashboard.cancelledOrders": "İptal",
        "dashboard.returnedOrders": "İade",
        "dashboard.orderNumber": "Sipariş No",
        "dashboard.marketplace": "Pazaryeri",
        "dashboard.amount": "Tutar",
        "dashboard.date": "Tarih",
        "dashboard.orderStatus": "Durum",
        "dashboard.unknownMarketplace": "Bilinmeyen Pazaryeri",

        // Notifications
        "notif.title": "Bildirimler",
        "notif.markAllRead": "Tümünü oku",
        "notif.clearAll": "Tümünü temizle",
        "notif.noNotifications": "Bildirim yok",
        "notif.new": "yeni",
        "notif.soundOn": "Ses açık",
        "notif.soundOff": "Ses kapalı",
        "notif.all": "Tümü",
        "notif.orders": "Siparişler",
        "notif.announcements": "Duyurular",
        "notif.ai": "AI",
        "notif.willAppearHere": "Siparişler, AI önerileri ve duyurular burada görünecek",
        "notif.order": "Sipariş",
        "notif.announcement": "Duyuru",
        "notif.stock": "Stok",
        "notif.system": "Sistem",

        // Orders Page
        "orders.pageTitle": "Sipariş Yönetimi",
        "orders.pageSubtitle": "Tüm pazaryerlerinden gelen siparişlerİşinizi tek ekrandan yönetin",
        "orders.scopedSubtitle": "Yalnızca bu pazaryeri — varsayılan son 7 gün (tarih aralığını aşağıdan değiştirebilirsiniz)",
        "orders.all": "Tümü",
        "orders.new": "Yeni",
        "orders.processing": "lemde",
        "orders.shipping": "Kargoda",
        "orders.deliver": "Teslim",
        "orders.cancel": "İptal",
        "orders.return": "İade",
        "orders.searchPlaceholder": "Sipariş no, mteri ad, takip no veya ürün ara...",
        "orders.allMarketplaces": "Tüm Pazaryerleri",
        "orders.loading": "Ykleniyor...",
        "orders.refresh": "Yenile",
        "orders.datePreset7": "Son 7 gün",
        "orders.datePreset30": "Son 30 gün",
        "orders.datePreset90": "Son 90 gün",
        "orders.clear": "Temizle",
        "orders.loadingOrders": "Siparişler ykleniyor...",
        "orders.fetchingOrders": "siparişleri ekiliyor...",
        "orders.showingOrders": "sipariş gösteriliyor",
        "orders.page": "Sayfa",
        "orders.orderNo": "Sipariş No",
        "orders.marketplace": "Pazaryeri",
        "orders.customer": "Mteri",
        "orders.products": "ürünler",
        "orders.amount": "Tutar",
        "orders.toInvoice": "Faturalanacak",
        "orders.grossSales": "Satış tutarı",
        "orders.sellerDiscount": "Satıcı indirimi",
        "orders.tyDiscount": "TY indirimi",
        "orders.priceBreakdown": "Tutar dökümü",
        "orders.date": "Tarih",
        "orders.status": "Durum",
        "orders.notFound": "Sipariş bulunamad",
        "orders.noOrdersYet": "Henüz hi sipariş yok veya pazaryeri entegrasyonlarnz kontrol edin",
        "orders.allMarketplacesFailed": "Hiçbir pazaryerinden sipariş alınamadı. Ağ bağlantınızı ve API / entegrasyon ayarlarını kontrol edin.",
        "orders.partialMarketplaceFailure": "Bazı pazaryerleri yüklenemedi:",
        "orders.noFilterMatch": "Filtre kriterlerinize uygun sipariş bulunamad",
        "orders.orderDetail": "Sipariş Detay",
        "orders.trackingNo": "Takip No",
        "orders.cargoCompany": "Kargo Firmas",
        "orders.unknown": "Bilinmiyor",
        "orders.none": "Yok",
        "orders.product": "rn",
        "orders.quantity": "Adet",
        "orders.price": "Fiyat",
        "orders.moreProducts": "ürün daha",
        "orders.noProductInfo": "ürün bilgisi bulunamad",
        "orders.totalLabel": "Toplam",
        "orders.revenue": "Ciro",
        "orders.newLabel": "Yeni",
        "orders.shippingLabel": "Kargoda",
        "orders.statusNew": "Yeni",
        "orders.statusProcessing": "lemde",
        "orders.statusShipping": "Kargoda",
        "orders.statusDelivered": "Teslim Edildi",
        "orders.statusCancelled": "İptal",
        "orders.statusReturned": "İade",

        // Orders Page  Invoice Status
        "orders.invoice": "Fatura",
        "orders.invoiceStatus": "Fatura Durumu",
        "orders.invoiced": "Fatural",
        "orders.uninvoiced": "Faturasz",
        "orders.invoicePending": "Bekliyor",
        "orders.invoiceError": "Hata",
        "orders.invoiceCreated": "Kesildi",
        "orders.allInvoice": "Tüm Fatura",
        "orders.invoiceNo": "Fatura No",
        "orders.viewInvoice": "Faturay Grntle",
        "orders.invoicedLabel": "Fatural",
        "orders.uninvoicedLabel": "Faturasz",
        "orders.invoiceErrorLabel": "Fatura Hatal",
        "orders.dbSource": "Veritabanından ykleniyor...",
        "orders.fromDb": "DB Siparişleri",
        "orders.fromApi": "API Siparişleri",
        "orders.switchToDb": "DB Grnm (Fatura Durumlu)",
        "orders.switchToApi": "API Grnm",
        "orders.cargoLabelTitle": "Kargo Etiketi",
        "orders.cargoLabelBtn": "Etiket",
        "orders.cargoLabelLoading": "Etiket yükleniyor...",
        "orders.cargoLabelPrint": "Yazdır",
        "orders.cargoLabelDownload": "İndir",
        "orders.cargoLabelError": "Kargo etiketi alınamadı.",
        "orders.cargoLabelPreviewFail": "Etiket önizlemesi oluşturulamadı; ZPL dosyasını indirip termal yazıcıdan yazdırabilirsiniz.",
        "orders.cargoLabelZplHint": "Termal yazıcı için ZPL dosyasını indirin.",

        // Finance Page
        "finance.pageTitle": "Finans Yönetimi",
        "finance.detailedAnalysis": "Detayl finansal analiz",
        "finance.selectMarketplace": "Pazaryeri sein",
        "finance.autoRefresh": "Oto Yenileme",
        "finance.on": "Ak",
        "finance.off": "Kapal",
        "finance.loading": "Ykleniyor...",
        "finance.refresh": "Yenile",
        "finance.noMarketplace": "Pazaryeri Entegrasyonu Bulunamad",
        "finance.noMarketplaceDesc": "Finans verilerini görüntlemek iin nce bir pazaryeri entegrasyonu eklemelisiniz.",
        "finance.overview": "Genel Bak",
        "finance.charts": "Grafikler",
        "finance.transactions": "lemler",
        "finance.errorOccurred": "Hata Olutu",
        "finance.apiNotSupported": "Finans API Henüz Desteklenmiyor",
        "finance.noMarketplaceSelected": "Pazaryeri Seilmedi",
        "finance.selectFromMenu": "Ltfen soldaki menden bir pazaryeri sein.",
        "finance.totalSales": "Toplam Sat",
        "finance.netRevenue": "Net Gelir",
        "finance.totalCommission": "Toplam Komisyon",
        "finance.netProfit": "Net Kr",
        "finance.returnRate": "İade Oran",
        "finance.avgBasket": "Ortalama Sepet",
        "finance.paymentsReceived": "deme Alnan",
        "finance.deductions": "Kesintiler",
        "finance.revenueTrend": "Gelir Trendi",
        "finance.orderCount": "Sipariş Says",
        "finance.commissionAnalysis": "Komisyon Analizi",
        "finance.transactionDist": "lem Dalm",
        "finance.allTransactions": "Tüm lemler",
        "finance.noTransactions": "Seilen tarih aralnda ilem bulunamad.",
        "finance.exportNoData": "Da aktarlacak veri yok!",
        "finance.financeDetails": "Finans Detaylar",
        "finance.lastUpdate": "Son",
        "finance.marketplace": "Pazaryeri:",
        "finance.orders": "sipariş",
        "finance.beforeCommission": "Komisyon ncesi",
        "finance.afterDeductions": "Tüm kesintiler sonras",
        "finance.returns": "iİade",
        "finance.perOrder": "Sipariş bana",
        "finance.toAccount": "Hesaba geen",
        "finance.cargoEtc": "Kargo, platform vb.",
        "finance.dateCol": "Tarih",
        "finance.orderNoCol": "Sipariş No",
        "finance.barcodeCol": "Barkod",
        "finance.typeCol": "lem Tipi",
        "finance.creditCol": "Alacak",
        "finance.debtCol": "Bor",
        "finance.commissionCol": "Komisyon",
        "finance.netRevenueCol": "Net Gelir",

        // Cargo Tracking Page
        "cargo.pageTitle": "Kargo Yönetimi",
        "cargo.trackingSystem": "Kargo takip ve yönetim sistemi",
        "cargo.cargo": "kargo",
        "cargo.update": "Güncelle",
        "cargo.loading": "Ykleniyor...",
        "cargo.total": "Toplam",
        "cargo.shipped": "Kargoda",
        "cargo.delivered": "Teslim Edildi",
        "cargo.returned": "İade",
        "cargo.undelivered": "Teslim Edilemedi",
        "cargo.all": "Tümü",
        "cargo.deliver": "Teslim",
        "cargo.searchPlaceholder": "Sipariş No, Mteri, Takip No...",
        "cargo.apply": "Uygula",
        "cargo.orderNo": "Sipariş No",
        "cargo.customer": "Mteri",
        "cargo.cargoCompany": "Kargo Firmas",
        "cargo.trackingNo": "Takip No",
        "cargo.date": "Tarih",
        "cargo.status": "Durum",
        "cargo.action": "lem",
        "cargo.track": "Takip",
        "cargo.loadingData": "Kargo verileri ykleniyor...",
        "cargo.notFound": "Kargo Bulunamad",
        "cargo.notFoundDesc": "iin kargo siparişi bulunamad.",
        "cargo.previous": "Önceki",
        "cargo.next": "Sonraki",
        "cargo.marketplace": "Pazaryeri",
        "cargo.orderDate": "Sipariş Tarihi",
        "cargo.productsLabel": "ürünler",
        "cargo.unknown": "Bilinmiyor",

        // Stock Management
        "stock.pageTitle": "Stok Yönetimi",
        "stock.products": "rn",
        "stock.refresh": "Yenile",
        "stock.totalProducts": "Toplam rn",
        "stock.sufficient": "Yeterli Stok",
        "stock.low": "Dk Stok",
        "stock.critical": "Kritik Stok",
        "stock.outOfStock": "Tkendi",
        "stock.searchPlaceholder": "ürün ad, barkod, kategori ara...",
        "stock.allStock": "Tüm Stok",
        "stock.sufficientFilter": "Yeterli (20+)",
        "stock.lowFilter": "Dk (6-20)",
        "stock.criticalFilter": "Kritik (1-5)",
        "stock.outFilter": "Tkendi (0)",
        "stock.results": "sonu",
        "stock.retryBtn": "Tekrar Dene",
        "stock.loadingProducts": "ürünler ykleniyor...",
        "stock.noProducts": "Henüz ürün bulunamad",
        "stock.noProductsDesc": "Bu pazaryerinde kaytl ürün bulunmuyor.",
        "stock.noFilterMatch": "Filtreye uygun ürün yok",
        "stock.noFilterMatchDesc": "Arama veya filtre kriterlerİşinizi değiştirin.",
        "stock.image": "Grsel",
        "stock.productName": "ürün Ad",
        "stock.barcode": "Barkod",
        "stock.category": "Kategori",
        "stock.colorSize": "Renk / Beden",
        "stock.price": "Fiyat",
        "stock.stockCol": "Stok",
        "stock.statusCol": "Durum",
        "stock.productDetail": "ürün Detay",
        "stock.noImage": "Grsel Yok",
        "stock.pieces": "İadet",
        "stock.commission": "Komisyon",
        "stock.productId": "ürün ID",
        "stock.stockCode": "Stok Kodu",
        "stock.color": "Renk",
        "stock.size": "Beden",
        "stock.deliveryTime": "Termin Sresi",
        "stock.brand": "Marka",
        "stock.description": "Aklama",
        "stock.attributes": "Özellikler",
        "stock.viewOnMarketplace": "Pazaryerinde Grntle",
        "stock.statusSufficient": "Yeterli",
        "stock.statusLow": "Dk",
        "stock.statusCritical": "Kritik",
        "stock.statusOut": "Tkendi",

        // Category Center
        "categoryCenter.title": "Kategori Merkezi",
        "categoryCenter.subtitle": "Master kategori eşleştirme tablosu — tüm pazaryerleri tek sayfada",
        "categoryCenter.loadError": "Eşleştirmeler yüklenirken hata oluştu",
        "categoryCenter.treeError": "Kategori ağacı yüklenemedi",
        "categoryCenter.connected": "Bağlı",
        "categoryCenter.notConnected": "Bağlı değil",
        "categoryCenter.notIntegrated": "Henüz entegre edilmemiş",
        "categoryCenter.integrateFirst": "Entegrasyonlar sayfasından bu pazaryerini ekleyin.",
        "categoryCenter.searchPlaceholder": "Kategori ara...",
        "categoryCenter.topCategories": "üst kategori",
        "categoryCenter.loadingCategories": "kategoriler yükleniyor...",
        "categoryCenter.noCategories": "Kategori bulunamadı",
        "categoryCenter.resultsFound": "sonuç bulundu",
        "categoryCenter.noResults": "için sonuç bulunamadı",
        "categoryCenter.selections": "Seçim",
        "categoryCenter.pickCategory": "Kategori seç",
        "categoryCenter.searchHint": "Kategori adı yazarak arayın (en az 2 karakter)",
        "categoryCenter.clickToMap": "Eşleştirmek için tıklayın",
        "categoryCenter.noData": "Eşleştirme verisi bulunamadı",
        "categoryCenter.importHint": "Önce import scriptini çalıştırarak Excel verilerini yükleyin.",
        "categoryCenter.totalRecords": "kayıt",
        "categoryCenter.statTotal": "Toplam satır",
        "categoryCenter.statUnique": "Benzersiz kategori",
        "categoryCenter.exportExcel": "Excel indir",

        // HB Categories
        "categoryCenter.hbCategories": "HB kategorileri",
        "categoryCenter.hbCategoriesDesc": "Hepsiburada kategori ağacı — dal yapısında görüntüleme ve Excel'e aktarma",
        "categoryCenter.loadingTree": "Kategori ağacı yükleniyor...",
        "categoryCenter.expandAll": "Tümünü aç",
        "categoryCenter.collapseAll": "Tümünü kapat",
        "categoryCenter.totalCategories": "Toplam kategori",
        "categoryCenter.rootCategories": "Kök kategori",
        "categoryCenter.leafCategories": "Yaprak kategori",
        "categoryCenter.categoryId": "Kategori ID",
        "categoryCenter.categoryName": "Kategori adı",
        "categoryCenter.isLeaf": "Yaprak",
        "categoryCenter.isAvailable": "Kullanılabilir",
        "categoryCenter.hasChildren": "Alt kategori",
        "categoryCenter.noHbIntegration": "Hepsiburada entegrasyonu bulunamadı",
        "categoryCenter.addHbFirst": "Önce Entegrasyonlar sayfasından Hepsiburada'yı ekleyin",
        "categoryCenter.exportHbExcel": "HB kategorileri Excel indir",

        // Billing Page
        "billing.pageTitle": "Faturalandırma",
        "billing.mpAutoInvoice": "Pazaryeri Bazlı Otomatik Fatura",
        "billing.mpAutoInvoiceDesc": "Her pazaryeri için otomatik faturayı ayrı ayrı açıp kapatabilirsiniz.",
        "billing.allMpActive": "Tüm pazaryerleri aktif",
        "billing.invoiced": "fatural",
        "billing.uninvoiced": "faturasız",
        "billing.invoiceRate": "Fatura oranı",
        "billing.mpStats": "Pazaryeri istatistikleri",
        "billing.totalInvoices": "Toplam Fatura",
        "billing.totalAmount": "Toplam Tutar",
        "billing.noMpSelected": "Hiçbir pazaryeri seçilmedi; tüm pazaryerlerinden gelen siparişler otomatik faturalanır.",

        // Marketplace Integration
        "mi.globalCenter": "Global Pazaryeri Entegrasyon Merkezi",
        "mi.dragHint": "Fareyi sürükleyerek uzayda gezinin, scroll ile yakınlaşın.",
        "mi.region": "Bölge",
        "mi.marketplace": "Pazaryeri",
        "mi.active": "Aktif",
        "mi.selectRegion": "Bölge Seçin",
        "mi.marketplaces": "pazaryeri",
        "mi.connected": "Bağlı",
        "mi.notConnected": "Bağlı Değil",
        "mi.update": "Güncelle",
        "mi.delete": "Sil",
        "mi.integrate": "Entegre Et",
        "mi.edit": "Düzenle",
        "mi.connect": "Bağlan",
        "mi.optional": "(opsiyonel)",
        "mi.authError": "Yetkilendirme hatası! Lütfen tekrar giriş yapın.",
        "mi.fillRequired": "Lütfen zorunlu API bilgilerini doldurun!",
        "mi.updated": "güncellendi!",
        "mi.integrationSuccess": "entegrasyonu başarılı!",
        "mi.serverError": "Sunucuya erişilemiyor.",
        "mi.deleteConfirm": "Entegrasyonu silmek istediğinize emin misiniz?",
        "mi.deleted": "silindi!",
        "mi.deleteFailed": "Silme başarısız!",

        // Auth pages
        "auth.loginTitle": "Giriş Yap",
        "auth.loginSubtitle": "Dashtock hesabınıza hoş geldiniz.",
        "auth.registerTitle": "Kayıt Ol",
        "auth.registerSubtitle": "Ücretsiz hesap oluşturun ve hemen başlayın.",
        "auth.emailPlaceholder": "E-posta adresiniz",
        "auth.passwordPlaceholder": "Şifreniz",
        "auth.namePlaceholder": "Adınız",
        "auth.surnamePlaceholder": "Soyadınız",
        "auth.phonePlaceholder": "Telefon numaranız (5XX XXX XX XX)",
        "auth.confirmPasswordPlaceholder": "Şifre Tekrar",
        "auth.loginBtn": "Giriş Yap",
        "auth.registerBtn": "Kayıt Ol",
        "auth.orDivider": "veya",
        "auth.googleContinue": "Google ile devam et",
        "auth.registerLink": "Kayıt olun",
        "auth.loginLink": "Giriş yapın",
        "auth.heroTitle1": "İşinizi tek panelden",
        "auth.heroTitle2": "yönetin,",
        "auth.heroTitle3": "büyütün.",
        "auth.heroDesc1": "Pazaryeri entegrasyonu, stok, sipariş ve daha fazlası.",
        "auth.heroDesc2": "Dashtock ile e-ticarette bir adım önde olun.",
        "auth.forgotTitle": "Şifremi Unuttum",
        "auth.forgotDesc": "Kayıtlı e-posta adresinizi girin, size bir sıfırlama kodu göndereceğiz.",
        "auth.sendCode": "Kod Gönder",
        "auth.backToLogin": "Giriş ekranına dön",
        "auth.verifyTitle": "Doğrulama Kodu",
        "auth.verifyDesc": "E-postanıza gönderilen 6 haneli kodu girin.",
        "auth.verifyCode": "Kodu Doğrula",
        "auth.goBack": "Geri dön",
        "auth.newPasswordTitle": "Yeni Şifre",
        "auth.newPasswordDesc": "Yeni şifrenizi belirleyin.",
        "auth.newPasswordPlaceholder": "Yeni şifre (min. 6 karakter)",
        "auth.confirmNewPlaceholder": "Şifrenizi tekrar girin",
        "auth.changePassword": "Şifreyi Değiştir",
        "auth.loginSuccess": "Giriş başarılı! Yönlendiriliyorsunuz...",
        "auth.googleLoginSuccess": "Google ile giriş başarılı!",
        "auth.registerSuccess": "Kayıt başarılı! Doğrulama e-postası gönderildi. Giriş sayfasına yönlendiriliyorsunuz...",
        "auth.googleRegisterSuccess": "Google ile kayıt başarılı!",
        "auth.passwordMismatch": "Şifreler eşleşmiyor!",
        "auth.passwordTooShort": "Şifre en az 8 karakter olmalıdır!",
        "auth.passwordNeedUpper": "Şifre en az bir büyük harf içermelidir.",
        "auth.passwordNeedLower": "Şifre en az bir küçük harf içermelidir.",
        "auth.passwordNeedDigit": "Şifre en az bir rakam içermelidir.",
        "auth.resetCodeSent": "Şifre sıfırlama kodu e-posta adresinize gönderildi.",
        "auth.codeVerified": "Kod doğrulandı! Yeni şifrenizi belirleyin.",
        "auth.passwordChanged": "Şifreniz başarıyla değiştirildi! Giriş yapabilirsiniz.",
        "auth.resendVerification": "Doğrulama e-postasını yeniden gönder",
        "auth.resending": "Gönderiliyor...",
        "auth.verificationResent": "Doğrulama e-postası yeniden gönderildi!",
        "auth.userLoadFailed": "Kullanıcı bilgileri yüklenemedi.",
    },
    en: {
        // Sidebar
        "sidebar.home": "Home",
        "sidebar.marketplace": "Marketplace",
        "sidebar.integrations": "Integrations",
        "sidebar.orders": "Order Management",
        "sidebar.returns": "Returns Management",
        "sidebar.inventory": "Inventory",
        "sidebar.shipping": "Shipping",
        "sidebar.finance": "Finance",
        "sidebar.productMgmt": "Product Management",
        "sidebar.productCenter": "Product Center",
        "sidebar.productUpload": "Upload & Distribute",
        "sidebar.categoryCenter": "Category Center",

        "sidebar.analytics": "Analytics & AI",
        "sidebar.advancedAnalytics": "Advanced Analytics",
        "sidebar.aiAssistant": "AI Assistant",
        "sidebar.roketfy": "Dashtock Radar",
        "sidebar.radarPro": "Opportunity Radar",
        "sidebar.management": "Management",
        "sidebar.userMgmt": "User Management",
        "sidebar.billing": "Billing",
        "sidebar.support": "Support Tickets",
        "sidebar.settings": "Settings",
        "sidebar.adminPanel": "Admin Panel",
        "sidebar.logout": "Sign Out",
        "sidebar.logoutConfirm": "Are you sure you want to sign out?",

        // Dashboard
        "dashboard.greeting.morning": "Good Morning",
        "dashboard.greeting.afternoon": "Good Afternoon",
        "dashboard.greeting.evening": "Good Evening",
        "dashboard.greeting.night": "Good Night",
        "dashboard.totalOrders": "Total Orders",
        "dashboard.totalRevenue": "Total Revenue",
        "dashboard.productCount": "Products",
        "dashboard.lowStock": "Low Stock",
        "dashboard.weeklyOrders": "7-Day Orders",
        "dashboard.delivered": "Delivered",
        "dashboard.new": "new",
        "dashboard.processing": "processing",
        "dashboard.shipping": "shipping",
        "dashboard.cancel": "cancelled",
        "dashboard.return": "returned",
        "dashboard.active": "Active",
        "dashboard.passive": "Passive",
        "dashboard.outOfStock": "out of stock",
        "dashboard.avgBasket": "Avg. basket",
        "dashboard.activeChannels": "Active Channels",
        "dashboard.errors": "Errors",
        "dashboard.pendingSync": "Pending Sync",
        "dashboard.stockMismatch": "Stock Mismatch",
        "dashboard.lastUpdate": "Last Update",
        "dashboard.recentOrders": "Recent Orders",
        "dashboard.viewAll": "View All ",
        "dashboard.noOrders": "No orders yet",
        "dashboard.alerts": "Alerts & Notifications",
        "dashboard.noAlerts": "No active alerts",
        "dashboard.channelRevenue": "Channel Revenue",
        "dashboard.quickActions": "Quick Actions",
        "dashboard.operationLogs": "Operation Logs",
        "dashboard.noLogs": "No operation logs yet",

        // Settings
        "settings.title": "Settings",
        "settings.subtitle": "Manage your app preferences and account settings",
        "settings.appearance": "Appearance",
        "settings.theme": "Theme",
        "settings.themeDesc": "Choose your interface theme",
        "settings.dark": "Dark",
        "settings.light": "Light",
        "settings.system": "System",
        "settings.language": "Language",
        "settings.languageDesc": "Choose your interface language",
        "settings.turkish": "Trke",
        "settings.english": "English",
        "settings.notifications": "Notifications",
        "settings.notifDesc": "Manage your notification preferences",
        "settings.orderNotif": "Order Notifications",
        "settings.orderNotifDesc": "Get notified when a new order arrives",
        "settings.stockNotif": "Stock Notifications",
        "settings.stockNotifDesc": "Get low stock alerts",
        "settings.soundNotif": "Sound Notifications",
        "settings.soundNotifDesc": "Play sound on new notifications",
        "settings.emailNotif": "Email Notifications",
        "settings.emailNotifDesc": "Receive important updates via email",
        "settings.account": "Account",
        "settings.accountDesc": "Manage your account information",
        "settings.name": "Full Name",
        "settings.email": "Email",
        "settings.phone": "Phone",
        "settings.company": "Company",
        "settings.save": "Save",
        "settings.saved": "Saved!",
        "settings.saving": "Saving...",
        "settings.security": "Security",
        "settings.securityDesc": "Manage your password and security settings",
        "settings.currentPassword": "Current Password",
        "settings.newPassword": "New Password",
        "settings.confirmPassword": "Confirm Password",
        "settings.changePassword": "Change Password",
        "settings.dangerZone": "Danger Zone",
        "settings.deleteAccount": "Delete Account",
        "settings.deleteAccountDesc": "This action cannot be undone. All your data will be permanently deleted.",
        "settings.subscription": "Subscription",
        "settings.plan": "Plan",
        "settings.planFree": "Free",
        "settings.planBasic": "Basic",
        "settings.planPro": "Professional",
        "settings.planEnterprise": "Enterprise",

        // Admin
        "admin.title": "Admin Panel",
        "admin.subtitle": "System management and user control",
        "admin.users": "Users",
        "admin.system": "System Status",
        "admin.logs": "System Logs",
        "admin.settings": "System Settings",
        "admin.totalUsers": "Total Users",
        "admin.activeToday": "Active Today",
        "admin.totalIntegrations": "Total Integrations",
        "admin.serverUptime": "Server Uptime",
        "admin.search": "Search users...",
        "admin.allRoles": "All Roles",
        "admin.role": "Role",
        "admin.registered": "Registered",
        "admin.actions": "Actions",
        "admin.edit": "Edit",
        "admin.delete": "Delete",
        "admin.impersonate": "Enter Panel",
        "admin.cpu": "CPU Usage",
        "admin.memory": "Memory Usage",
        "admin.database": "Database",
        "admin.connected": "Connected",
        "admin.disconnected": "Disconnected",
        "admin.nodeVersion": "Node.js",
        "admin.platform": "Platform",
        "admin.hostname": "Hostname",
        "admin.noLogs": "No logs found",

        // Auth & 2FA
        "auth.login": "Sign In",
        "auth.register": "Sign Up",
        "auth.logout": "Sign Out",
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.forgotPassword": "Forgot Password",
        "auth.rememberMe": "Remember Me",
        "auth.noAccount": "Don't have an account?",
        "auth.hasAccount": "Already have an account?",
        "auth.2fa.title": "Two-Factor Authentication",
        "auth.2fa.subtitle": "Enter the 6-digit code sent to your email",
        "auth.2fa.code": "Verification Code",
        "auth.2fa.verify": "Verify",
        "auth.2fa.resend": "Resend Code",
        "auth.2fa.backupCode": "Use backup code",
        "auth.2fa.enable": "Enable 2FA",
        "auth.2fa.disable": "Disable 2FA",
        "auth.2fa.enabled": "Two-factor authentication is active",
        "auth.2fa.disabled": "Two-factor authentication is disabled",

        // Marketplace
        "marketplace.title": "Marketplace Integrations",
        "marketplace.add": "Add Integration",
        "marketplace.test": "Test Connection",
        "marketplace.connected": "Connected",
        "marketplace.disconnected": "Disconnected",
        "marketplace.credentials": "API Credentials",
        "marketplace.sync": "Synchronize",
        "marketplace.lastSync": "Last Sync",

        // Products
        "products.title": "Products",
        "products.total": "Total Products",
        "products.active": "Active",
        "products.passive": "Passive",
        "products.outOfStock": "Out of Stock",
        "products.search": "Search products...",
        "products.export": "Export",
        "products.import": "Import",
        "products.create": "New Product",
        "products.distribute": "Distribute",
        "products.bulkActions": "Bulk Actions",

        // Orders
        "orders.title": "Orders",
        "orders.total": "Total Orders",
        "orders.pending": "Pending",
        "orders.shipped": "Shipped",
        "orders.delivered": "Delivered",
        "orders.cancelled": "Cancelled",
        "orders.returned": "Returned",

        // Finance
        "finance.title": "Finance",
        "finance.revenue": "Revenue",
        "finance.expense": "Expense",
        "finance.profit": "Profit",
        "finance.commission": "Commission",
        "finance.settlement": "Settlement",

        // AI
        "ai.title": "AI Assistant",
        "ai.suggestions": "Suggestions",
        "ai.score": "AI Score",
        "ai.optimize": "Optimize",
        "ai.simulate": "Simulate",
        "ai.brain": "AI Brain",
        "ai.chat": "AI Chat",

        // Common
        "common.loading": "Loading...",
        "common.error": "An error occurred",
        "common.retry": "Retry",
        "common.cancel": "Cancel",
        "common.confirm": "Confirm",
        "common.close": "Close",
        "common.yes": "Yes",
        "common.no": "No",
        "common.save": "Save",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.search": "Search...",
        "common.filter": "Filter",
        "common.export": "Export",
        "common.import": "Import",
        "common.refresh": "Refresh",
        "common.back": "Back",
        "common.next": "Next",
        "common.previous": "Previous",
        "common.noData": "No data found",
        "common.success": "Operation successful",
        "common.total": "Total",

        // Dashboard Extended
        "dashboard.error": "Error",
        "dashboard.lowStockAlert": "Low Stock",
        "dashboard.marketplaceStatus": "Marketplace Status",
        "dashboard.channel": "Channel",
        "dashboard.status": "Status",
        "dashboard.orders": "Orders",
        "dashboard.revenue": "Revenue",
        "dashboard.slow": "Slow",
        "dashboard.unknown": "Unknown",
        "dashboard.weeklyTrend": "7-Day Trend",
        "dashboard.productHealth": "Product & Stock Health",
        "dashboard.totalProducts": "Total Products",
        "dashboard.activeProducts": "Active Products",
        "dashboard.stockMismatchCount": "Stock Mismatch",
        "dashboard.allSystemsNormal": "All systems normal",
        "dashboard.noData": "No data",
        "dashboard.orderManagement": "Order Management",
        "dashboard.stockManagement": "Stock Management",
        "dashboard.productCenter": "Product Center",
        "dashboard.integrations": "Integrations",
        "dashboard.finance": "Finance",
        "dashboard.viewAllLogs": "View All ",
        "dashboard.showingOrders": "orders showing",
        "dashboard.goToOrderManagement": "Go to Order Management ",
        "dashboard.noCategoryOrders": "No orders found in this category",
        "dashboard.marketplaceDistribution": "Marketplace Product Distribution",
        "dashboard.synced": "synced",
        "dashboard.errorProducts": "errors",
        "dashboard.all": "All",
        "dashboard.newOrders": "New",
        "dashboard.processingOrders": "Processing",
        "dashboard.shippingOrders": "Shipping",
        "dashboard.deliveredOrders": "Delivered",
        "dashboard.cancelledOrders": "Cancelled",
        "dashboard.returnedOrders": "Returned",
        "dashboard.orderNumber": "Order No",
        "dashboard.marketplace": "Marketplace",
        "dashboard.amount": "Amount",
        "dashboard.date": "Date",
        "dashboard.orderStatus": "Status",
        "dashboard.unknownMarketplace": "Unknown Marketplace",

        // Notifications
        "notif.title": "Notifications",
        "notif.markAllRead": "Mark All as Read",
        "notif.clearAll": "Clear All",
        "notif.noNotifications": "No notifications",
        "notif.new": "new",
        "notif.soundOn": "",
        "notif.soundOff": "",
        "notif.all": "All",
        "notif.orders": "Orders",
        "notif.announcements": "Announcements",
        "notif.ai": "AI",
        "notif.willAppearHere": "Orders, AI suggestions and announcements will appear here",
        "notif.order": "Order",
        "notif.announcement": "Announcement",
        "notif.stock": "Stock",
        "notif.system": "System",

        // Orders Page
        "orders.pageTitle": "Order Management",
        "orders.pageSubtitle": "Manage all your marketplace orders from a single screen",
        "orders.scopedSubtitle": "This marketplace only — default last 7 days (change the range below)",
        "orders.all": "All",
        "orders.new": "New",
        "orders.processing": "Processing",
        "orders.shipping": "Shipping",
        "orders.deliver": "Delivered",
        "orders.cancel": "Cancelled",
        "orders.return": "Returned",
        "orders.searchPlaceholder": "Search order no, customer, tracking no or product...",
        "orders.allMarketplaces": "All Marketplaces",
        "orders.loading": "Loading...",
        "orders.refresh": "Refresh",
        "orders.datePreset7": "Last 7 days",
        "orders.datePreset30": "Last 30 days",
        "orders.datePreset90": "Last 90 days",
        "orders.clear": "Clear",
        "orders.loadingOrders": "Loading orders...",
        "orders.fetchingOrders": "fetching orders...",
        "orders.showingOrders": "orders showing",
        "orders.page": "Page",
        "orders.orderNo": "Order No",
        "orders.marketplace": "Marketplace",
        "orders.customer": "Customer",
        "orders.products": "Products",
        "orders.amount": "Amount",
        "orders.toInvoice": "Net (invoice)",
        "orders.grossSales": "Gross sales",
        "orders.sellerDiscount": "Seller discount",
        "orders.tyDiscount": "Marketplace discount",
        "orders.priceBreakdown": "Amount breakdown",
        "orders.date": "Date",
        "orders.status": "Status",
        "orders.notFound": "No orders found",
        "orders.noOrdersYet": "No orders yet or check your marketplace integrations",
        "orders.allMarketplacesFailed": "Could not load orders from any marketplace. Check your network and API / integration settings.",
        "orders.partialMarketplaceFailure": "Some marketplaces failed to load:",
        "orders.noFilterMatch": "No orders match your filter criteria",
        "orders.orderDetail": "Order Detail",
        "orders.trackingNo": "Tracking No",
        "orders.cargoCompany": "Cargo Company",
        "orders.unknown": "Unknown",
        "orders.none": "None",
        "orders.product": "Product",
        "orders.quantity": "Qty",
        "orders.price": "Price",
        "orders.moreProducts": "more products",
        "orders.noProductInfo": "No product information found",
        "orders.totalLabel": "Total",
        "orders.revenue": "Revenue",
        "orders.newLabel": "New",
        "orders.shippingLabel": "Shipping",
        "orders.statusNew": "New",
        "orders.statusProcessing": "Processing",
        "orders.statusShipping": "Shipping",
        "orders.statusDelivered": "Delivered",
        "orders.statusCancelled": "Cancelled",
        "orders.statusReturned": "Returned",

        // Orders Page  Invoice Status
        "orders.invoice": "Invoice",
        "orders.invoiceStatus": "Invoice Status",
        "orders.invoiced": "Invoiced",
        "orders.uninvoiced": "No Invoice",
        "orders.invoicePending": "Pending",
        "orders.invoiceError": "Error",
        "orders.invoiceCreated": "Created",
        "orders.allInvoice": "All Invoice",
        "orders.invoiceNo": "Invoice No",
        "orders.viewInvoice": "View Invoice",
        "orders.invoicedLabel": "Invoiced",
        "orders.uninvoicedLabel": "No Invoice",
        "orders.invoiceErrorLabel": "Invoice Error",
        "orders.dbSource": "Loading from database...",
        "orders.fromDb": "DB Orders",
        "orders.fromApi": "API Orders",
        "orders.switchToDb": "DB View (With Invoice Status)",
        "orders.switchToApi": "API View",
        "orders.cargoLabelTitle": "Shipping Label",
        "orders.cargoLabelBtn": "Label",
        "orders.cargoLabelLoading": "Loading label...",
        "orders.cargoLabelPrint": "Print",
        "orders.cargoLabelDownload": "Download",
        "orders.cargoLabelError": "Could not fetch shipping label.",
        "orders.cargoLabelPreviewFail": "Preview failed; download the ZPL file for your thermal printer.",
        "orders.cargoLabelZplHint": "Download the ZPL file for your thermal printer.",

        // Finance Page
        "finance.pageTitle": "Finance Management",
        "finance.detailedAnalysis": "Detailed financial analysis",
        "finance.selectMarketplace": "Select marketplace",
        "finance.autoRefresh": "Auto Refresh",
        "finance.on": "On",
        "finance.off": "Off",
        "finance.loading": "Loading...",
        "finance.refresh": "Refresh",
        "finance.noMarketplace": "No Marketplace Integration Found",
        "finance.noMarketplaceDesc": "You need to add a marketplace integration first to view finance data.",
        "finance.overview": "Overview",
        "finance.charts": "Charts",
        "finance.transactions": "Transactions",
        "finance.errorOccurred": "Error Occurred",
        "finance.apiNotSupported": "Finance API Not Yet Supported",
        "finance.noMarketplaceSelected": "No Marketplace Selected",
        "finance.selectFromMenu": "Please select a marketplace from the menu.",
        "finance.totalSales": "Total Sales",
        "finance.netRevenue": "Net Revenue",
        "finance.totalCommission": "Total Commission",
        "finance.netProfit": "Net Profit",
        "finance.returnRate": "Return Rate",
        "finance.avgBasket": "Average Basket",
        "finance.paymentsReceived": "Payments Received",
        "finance.deductions": "Deductions",
        "finance.revenueTrend": "Revenue Trend",
        "finance.orderCount": "Order Count",
        "finance.commissionAnalysis": "Commission Analysis",
        "finance.transactionDist": "Transaction Distribution",
        "finance.allTransactions": "All Transactions",
        "finance.noTransactions": "No transactions found in the selected date range.",
        "finance.exportNoData": "No data to export!",
        "finance.financeDetails": "Finance Details",
        "finance.lastUpdate": "Last",
        "finance.marketplace": "Marketplace:",
        "finance.orders": "orders",
        "finance.beforeCommission": "Before commission",
        "finance.afterDeductions": "After all deductions",
        "finance.returns": "returns",
        "finance.perOrder": "Per order",
        "finance.toAccount": "To account",
        "finance.cargoEtc": "Cargo, platform etc.",
        "finance.dateCol": "Date",
        "finance.orderNoCol": "Order No",
        "finance.barcodeCol": "Barcode",
        "finance.typeCol": "Transaction Type",
        "finance.creditCol": "Credit",
        "finance.debtCol": "Debt",
        "finance.commissionCol": "Commission",
        "finance.netRevenueCol": "Net Revenue",

        // Cargo Tracking Page
        "cargo.pageTitle": "Cargo Management",
        "cargo.trackingSystem": "Cargo tracking and management system",
        "cargo.cargo": "cargo",
        "cargo.update": "Update",
        "cargo.loading": "Loading...",
        "cargo.total": "Total",
        "cargo.shipped": "Shipped",
        "cargo.delivered": "Delivered",
        "cargo.returned": "Returned",
        "cargo.undelivered": "Undelivered",
        "cargo.all": "All",
        "cargo.deliver": "Delivered",
        "cargo.searchPlaceholder": "Order No, Customer, Tracking No...",
        "cargo.apply": "Apply",
        "cargo.orderNo": "Order No",
        "cargo.customer": "Customer",
        "cargo.cargoCompany": "Cargo Company",
        "cargo.trackingNo": "Tracking No",
        "cargo.date": "Date",
        "cargo.status": "Status",
        "cargo.action": "Action",
        "cargo.track": "Track",
        "cargo.loadingData": "Loading cargo data...",
        "cargo.notFound": "No Cargo Found",
        "cargo.notFoundDesc": "no cargo orders found.",
        "cargo.previous": "Previous",
        "cargo.next": "Next",
        "cargo.marketplace": "Marketplace",
        "cargo.orderDate": "Order Date",
        "cargo.productsLabel": "Products",
        "cargo.unknown": "Unknown",

        // Stock Management
        "stock.pageTitle": "Stock Management",
        "stock.products": "products",
        "stock.refresh": "Refresh",
        "stock.totalProducts": "Total Products",
        "stock.sufficient": "Sufficient Stock",
        "stock.low": "Low Stock",
        "stock.critical": "Critical Stock",
        "stock.outOfStock": "Out of Stock",
        "stock.searchPlaceholder": "Search product name, barcode, category...",
        "stock.allStock": "All Stock",
        "stock.sufficientFilter": "Sufficient (20+)",
        "stock.lowFilter": "Low (6-20)",
        "stock.criticalFilter": "Critical (1-5)",
        "stock.outFilter": "Out of Stock (0)",
        "stock.results": "results",
        "stock.retryBtn": "Retry",
        "stock.loadingProducts": "Loading products...",
        "stock.noProducts": "No products found",
        "stock.noProductsDesc": "No products registered in this marketplace.",
        "stock.noFilterMatch": "No products match filter",
        "stock.noFilterMatchDesc": "Change your search or filter criteria.",
        "stock.image": "Image",
        "stock.productName": "Product Name",
        "stock.barcode": "Barcode",
        "stock.category": "Category",
        "stock.colorSize": "Color / Size",
        "stock.price": "Price",
        "stock.stockCol": "Stock",
        "stock.statusCol": "Status",
        "stock.productDetail": "Product Detail",
        "stock.noImage": "No Image",
        "stock.pieces": "pcs",
        "stock.commission": "Commission",
        "stock.productId": "Product ID",
        "stock.stockCode": "Stock Code",
        "stock.color": "Color",
        "stock.size": "Size",
        "stock.deliveryTime": "Delivery Time",
        "stock.brand": "Brand",
        "stock.description": "Description",
        "stock.attributes": "Attributes",
        "stock.viewOnMarketplace": "View on Marketplace",
        "stock.statusSufficient": "Sufficient",
        "stock.statusLow": "Low",
        "stock.statusCritical": "Critical",
        "stock.statusOut": "Out of Stock",

        // Category Center
        "categoryCenter.title": "Category Center",
        "categoryCenter.subtitle": "Master category mapping table  all marketplaces on a single page",
        "categoryCenter.loadError": "Failed to load mappings",
        "categoryCenter.treeError": "Failed to load category tree",
        "categoryCenter.connected": "Connected",
        "categoryCenter.notConnected": "Not Connected",
        "categoryCenter.notIntegrated": "Not integrated yet",
        "categoryCenter.integrateFirst": "Connect this marketplace from the Integrations page.",
        "categoryCenter.searchPlaceholder": "Search categories...",
        "categoryCenter.topCategories": "top categories",
        "categoryCenter.loadingCategories": "categories loading...",
        "categoryCenter.noCategories": "No categories found",
        "categoryCenter.resultsFound": "results found",
        "categoryCenter.noResults": "no results found for",
        "categoryCenter.selections": "Selection",
        "categoryCenter.pickCategory": "Pick Category",
        "categoryCenter.searchHint": "Type a category name to search (min 2 characters)",
        "categoryCenter.clickToMap": "Click to map",
        "categoryCenter.noData": "No mapping data found",
        "categoryCenter.importHint": "Run the import script first to load Excel data.",
        "categoryCenter.totalRecords": "records",
        "categoryCenter.statTotal": "Total Rows",
        "categoryCenter.statUnique": "Unique Categories",
        "categoryCenter.exportExcel": "Export Excel",

        // HB Categories
        "categoryCenter.hbCategories": "HB Categories",
        "categoryCenter.hbCategoriesDesc": "Hepsiburada category tree  branch view and Excel export",
        "categoryCenter.loadingTree": "Loading category tree...",
        "categoryCenter.expandAll": "Expand All",
        "categoryCenter.collapseAll": "Collapse All",
        "categoryCenter.totalCategories": "Total Categories",
        "categoryCenter.rootCategories": "Root Categories",
        "categoryCenter.leafCategories": "Leaf Categories",
        "categoryCenter.categoryId": "Category ID",
        "categoryCenter.categoryName": "Category Name",
        "categoryCenter.isLeaf": "Leaf",
        "categoryCenter.isAvailable": "Available",
        "categoryCenter.hasChildren": "Has Children",
        "categoryCenter.noHbIntegration": "Hepsiburada integration not found",
        "categoryCenter.addHbFirst": "Please add Hepsiburada from Integrations page first",
        "categoryCenter.exportHbExcel": "Export HB Categories Excel",

        // Billing Page
        "billing.pageTitle": "Billing",
        "billing.mpAutoInvoice": "Per-Marketplace Auto Invoice",
        "billing.mpAutoInvoiceDesc": "Enable/disable auto invoice per marketplace.",
        "billing.allMpActive": "All marketplaces active",
        "billing.invoiced": "invoiced",
        "billing.uninvoiced": "uninvoiced",
        "billing.invoiceRate": "Invoice rate",
        "billing.mpStats": "Marketplace Statistics",
        "billing.totalInvoices": "Total Invoices",
        "billing.totalAmount": "Total Amount",
        "billing.noMpSelected": "No marketplace selected  orders from all marketplaces will be auto-invoiced.",

        // Marketplace Integration
        "mi.globalCenter": "Global Marketplace Integration Center",
        "mi.dragHint": "Drag to explore space  Scroll to zoom",
        "mi.region": "Region",
        "mi.marketplace": "Marketplace",
        "mi.active": "Active",
        "mi.selectRegion": "Select Region",
        "mi.marketplaces": "marketplaces",
        "mi.connected": "Connected",
        "mi.notConnected": "Not Connected",
        "mi.update": "Update",
        "mi.delete": "Delete",
        "mi.integrate": "Integrate",
        "mi.edit": "Edit",
        "mi.connect": "Connect",
        "mi.optional": "(optional)",
        "mi.authError": "Authorization error! Please login again.",
        "mi.fillRequired": "Please fill in the required API credentials!",
        "mi.updated": "updated!",
        "mi.integrationSuccess": "integration successful!",
        "mi.serverError": "Cannot reach server.",
        "mi.deleteConfirm": "Are you sure you want to delete this integration?",
        "mi.deleted": "deleted!",
        "mi.deleteFailed": "Delete failed!",

        // Auth pages
        "auth.loginTitle": "Sign In",
        "auth.loginSubtitle": "Welcome to your Dashtock account.",
        "auth.registerTitle": "Sign Up",
        "auth.registerSubtitle": "Create a free account and get started.",
        "auth.emailPlaceholder": "Your email address",
        "auth.passwordPlaceholder": "Your password",
        "auth.namePlaceholder": "First Name",
        "auth.surnamePlaceholder": "Last Name",
        "auth.phonePlaceholder": "Phone number",
        "auth.confirmPasswordPlaceholder": "Confirm Password",
        "auth.loginBtn": "Sign In",
        "auth.registerBtn": "Sign Up",
        "auth.orDivider": "or",
        "auth.googleContinue": "Continue with Google",
        "auth.registerLink": "Sign up",
        "auth.loginLink": "Sign in",
        "auth.heroTitle1": "Manage your business",
        "auth.heroTitle2": "from one panel,",
        "auth.heroTitle3": "grow it.",
        "auth.heroDesc1": "Marketplace integration, stock, orders and more.",
        "auth.heroDesc2": "Stay ahead in e-commerce with Dashtock.",
        "auth.forgotTitle": "Forgot Password",
        "auth.forgotDesc": "Enter your registered email address and we'll send you a reset code.",
        "auth.sendCode": "Send Code",
        "auth.backToLogin": "Back to login",
        "auth.verifyTitle": "Verification Code",
        "auth.verifyDesc": "Enter the 6-digit code sent to your email.",
        "auth.verifyCode": "Verify Code",
        "auth.goBack": "Go back",
        "auth.newPasswordTitle": "New Password",
        "auth.newPasswordDesc": "Set your new password.",
        "auth.newPasswordPlaceholder": "New password (min. 6 characters)",
        "auth.confirmNewPlaceholder": "Confirm your password",
        "auth.changePassword": "Change Password",
        "auth.loginSuccess": "Login successful! Redirecting...",
        "auth.googleLoginSuccess": "Google login successful!",
        "auth.registerSuccess": "Registration successful! Verification email sent. Redirecting to login...",
        "auth.googleRegisterSuccess": "Google registration successful!",
        "auth.passwordMismatch": "Passwords do not match!",
        "auth.passwordTooShort": "Password must be at least 8 characters!",
        "auth.passwordNeedUpper": "Password must contain at least one uppercase letter.",
        "auth.passwordNeedLower": "Password must contain at least one lowercase letter.",
        "auth.passwordNeedDigit": "Password must contain at least one digit.",
        "auth.resetCodeSent": "Password reset code sent to your email.",
        "auth.codeVerified": "Code verified! Set your new password.",
        "auth.passwordChanged": "Password changed successfully! You can now sign in.",
        "auth.resendVerification": "Resend verification email",
        "auth.resending": "Sending...",
        "auth.verificationResent": "Verification email resent!",
        "auth.userLoadFailed": "Failed to load user information.",
    }
};

/* 
   TEMA PALETLER
    */
const themes = {
    dark: {
        bg: "#0f1419",
        card: "rgba(26, 31, 53, 0.85)",
        border: "rgba(78, 205, 196, 0.18)",
        accent: "#4ecdc4",
        green: "#22c55e",
        red: "#ef4444",
        yellow: "#f59e0b",
        purple: "#8b5cf6",
        blue: "#06b6d4",
        pink: "#ec4899",
        text: "#e2e8f0",
        muted: "#94a3b8",
        dim: "#64748b",
        glass: "rgba(255,255,255,0.03)",
        glassBr: "rgba(255,255,255,0.06)",
        sidebarBg: "rgba(10, 13, 24, 0.97)",
        contentBg: "rgba(14, 18, 30, 0.9)",
        particleBg: "#0a0e1a",
        inputBg: "rgba(255,255,255,0.05)",
        inputBorder: "rgba(255,255,255,0.06)",
        hoverBg: "rgba(255,255,255,0.06)",
    },
    light: {
        bg: "#f0f2f5",
        card: "rgba(255, 255, 255, 0.92)",
        border: "rgba(78, 205, 196, 0.25)",
        accent: "#0d9488",
        green: "#16a34a",
        red: "#dc2626",
        yellow: "#d97706",
        purple: "#7c3aed",
        blue: "#0891b2",
        pink: "#db2777",
        text: "#1e293b",
        muted: "#64748b",
        dim: "#94a3b8",
        glass: "rgba(0,0,0,0.02)",
        glassBr: "rgba(0,0,0,0.08)",
        sidebarBg: "rgba(255, 255, 255, 0.97)",
        contentBg: "rgba(240, 242, 245, 0.95)",
        particleBg: "#e8ecf1",
        inputBg: "rgba(0,0,0,0.04)",
        inputBorder: "rgba(0,0,0,0.1)",
        hoverBg: "rgba(0,0,0,0.04)",
    }
};

/* 
   CONTEXT
    */
const AppContext = createContext();

const validateTranslations = () => {
    try {
        const trKeys = new Set(Object.keys(translations.tr || {}));
        const enKeys = new Set(Object.keys(translations.en || {}));
        const missingInEn = [...trKeys].filter((k) => !enKeys.has(k));
        const missingInTr = [...enKeys].filter((k) => !trKeys.has(k));

        if (missingInEn.length > 0) {
            console.warn(`[i18n] EN eksik anahtar sayısı: ${missingInEn.length}`);
        }
        if (missingInTr.length > 0) {
            console.warn(`[i18n] TR eksik anahtar sayısı: ${missingInTr.length}`);
        }
    } catch (e) {
        console.warn("[i18n] doğrulama çalıştırılamadı:", e.message);
    }
};

export const AppProvider = ({ children }) => {
    // Tema
    const [themeMode, setThemeMode] = useState(() => localStorage.getItem("themeMode") || "dark");
    const [systemTheme, setSystemTheme] = useState(() =>
        window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"
    );

    // Dil
    const [language, setLanguageState] = useState(() => localStorage.getItem("language") || "tr");

    // Sistem temas dinle
    useEffect(() => {
        const mq = window.matchMedia("(prefers-color-scheme: dark)");
        const handler = (e) => setSystemTheme(e.matches ? "dark" : "light");
        mq.addEventListener("change", handler);
        return () => mq.removeEventListener("change", handler);
    }, []);

    // Aktif tema hesapla
    const resolvedTheme = themeMode === "system" ? systemTheme : themeMode;
    const theme = themes[resolvedTheme] || themes.dark;

    // Tema değiştir
    const setTheme = useCallback((mode) => {
        setThemeMode(mode);
        localStorage.setItem("themeMode", mode);
    }, []);

    // Dil değiştir
    const setLanguage = useCallback((lang) => {
        setLanguageState(lang);
        localStorage.setItem("language", lang);
    }, []);

    // eviri fonksiyonu
    const t = useCallback((key) => {
        return translations[language]?.[key] || translations.tr[key] || translations.en[key] || key;
    }, [language]);

    useEffect(() => {
        if (process.env.NODE_ENV === "development") {
            validateTranslations();
        }
    }, []);

    // CSS deikenlerini uygula
    useEffect(() => {
        const root = document.documentElement;
        root.setAttribute("data-theme", resolvedTheme);

        // Sidebar ve content area renkleri CSS'e yanst
        root.style.setProperty("--app-sidebar-bg", theme.sidebarBg);
        root.style.setProperty("--app-content-bg", theme.contentBg);
        root.style.setProperty("--app-text", theme.text);
        root.style.setProperty("--app-muted", theme.muted);
        root.style.setProperty("--app-accent", theme.accent);
        root.style.setProperty("--app-border", theme.border);
        root.style.setProperty("--app-glass", theme.glass);
        root.style.setProperty("--app-glassBr", theme.glassBr);
        root.style.setProperty("--app-hover-bg", theme.hoverBg);
        root.style.setProperty("--app-input-bg", theme.inputBg);
        root.style.setProperty("--app-input-border", theme.inputBorder);
        root.style.setProperty("--app-particle-bg", theme.particleBg);
    }, [resolvedTheme, theme]);

    return (
        <AppContext.Provider value={{
            // Tema
            themeMode,
            resolvedTheme,
            theme,
            setTheme,
            themes,

            // Dil
            language,
            setLanguage,
            t,

            // eviri szl (direkt erişim)
            translations,
        }}>
            {children}
        </AppContext.Provider>
    );
};

export const useApp = () => {
    const ctx = useContext(AppContext);
    if (!ctx) throw new Error("useApp must be used within AppProvider");
    return ctx;
};

export default AppContext;

