/**
 * Panel / menü → paket özellik kilidi (backend planFeatureRegistry ile uyumlu)
 */
export const MENU_FEATURE_MAP = {
    dashboard: "dashboard",
    integration: "products",
    orders: "orders",
    inventory: "inventory",
    shipping: "shipping",
    finance: "finance_basic",
    "pm-center": "products",
    "product-upload": "product_upload",
    "website-builder": "website_builder",
    "website-builder-link": "website_builder",
    "store-hub": "own_storefront",
    ecommerce: "own_storefront",
    "ec-home": "own_storefront",
    "ec-products": "products",
    "ec-orders": "orders",
    "ec-customers": "own_storefront",
    "ec-discounts": "own_storefront",
    "ec-discounts-campaigns": "own_storefront",
    "ec-discounts-coupons": "own_storefront",
    "ec-inbox": "own_storefront",
    "ec-inbox-messages": "own_storefront",
    "ec-inbox-settings": "own_storefront",
    "ec-reports": "profit_analytics",
    "ec-settings": "dashboard",
    "store-hub": "own_storefront",
    "store-design": "own_storefront",
    "store-domain": "own_storefront",
    "store-products": "own_storefront",
    "store-orders": "own_storefront",
    "store-payments": "store_checkout",
    "category-center": "category_center",
    "advanced-analytics": "profit_analytics",
    "lysia-brain": "ai_assistant",
    roketfy: "roketfy",
    "radar-pro": "ai_radar",
    billing: "e_invoice",
    users: "dashboard",
    marketing: "store_marketing",
    "mkt-dashboard": "store_marketing",
    "mkt-campaigns-email": "store_marketing",
    "mkt-campaigns-sms": "store_marketing",
    "mkt-automations": "store_marketing",
    "mkt-segments": "store_marketing",
    "mkt-popups": "store_marketing",
    "mkt-affiliate": "store_marketing",
    "mkt-reports": "store_marketing",
    "mkt-settings": "store_marketing",
};

export const FEATURE_LABELS_TR = {
    ai_assistant: "AI Asistan",
    ai_radar: "Fırsat Radarı",
    roketfy: "Roketfy",
    e_invoice: "E-fatura",
    profit_analytics: "Gelişmiş kâr analizi",
    category_auto_match: "Akıllı kategori eşleştirme",
    product_upload: "Ürün yükleme",
    shipping: "Kargo takibi"
};
