"use strict";

const { getThemeAssets } = require("./storefrontThemeAssets");

/**
 * Dikey bazlı gerçekçi e-ticaret vitrin içeriği — tüm temalar için.
 */
const VERTICALS = {
    beauty: {
        tagline: "Doğal güzellik & bakım",
        heroSub: "Dermatolojik test edilmiş formüller, hızlı teslimat ve güvenli ödeme.",
        promoText: "500 ₺ üzeri siparişlerde ücretsiz kargo + 2 numune hediye",
        collections: [
            ["Cilt Bakımı", "/collections/cilt-bakimi", "Serum, nemlendirici, SPF"],
            ["Makyaj", "/collections/makyaj", "Ruj, fondöten, palet"],
            ["Saç Bakımı", "/collections/sac", "Şampuan, maske, yağ"],
            ["Parfüm", "/collections/parfum", "Kadın & erkek kokular"],
            ["Yeni Gelenler", "/collections/yeni", "Bu haftanın lansmanları"],
            ["Çok Satanlar", "/collections/cok-satan", "Müşteri favorileri"],
            ["İndirim", "/collections/indirim", "%40'a varan fırsatlar"],
            ["Setler", "/collections/setler", "Hediye setleri"],
        ],
        products: [
            { name: "Hyaluronik Nem Serumu 30ml", price: "₺649", old: "₺899", badge: "Çok Satan" },
            { name: "Vitamin C Aydınlatıcı Serum", price: "₺749", old: "₺999", badge: "Yeni" },
            { name: "SPF 50 Güneş Kremi", price: "₺549", badge: "" },
            { name: "Gece Onarım Kremi", price: "₺899", old: "₺1.199", badge: "İndirim" },
            { name: "Mat Ruj — Rose Nude", price: "₺399", badge: "" },
            { name: "Fondöten — Medium Beige", price: "₺599", badge: "Çok Satan" },
            { name: "Kaş & Kirpik Serumu", price: "₺329", badge: "" },
            { name: "Saç Bakım Yağı 100ml", price: "₺449", old: "₺599", badge: "" },
            { name: "Vücut Losyonu — Shea", price: "₺379", badge: "" },
            { name: "Peeling Tonik", price: "₺299", badge: "Yeni" },
            { name: "Göz Çevresi Kremi", price: "₺519", badge: "" },
            { name: "Parfüm — Floral Bloom 50ml", price: "₺1.290", badge: "Premium" },
        ],
        blog: [
            ["Kış aylarında cilt bakım rutini", "Cilt bakımı", "6 dk", "Kuru havada nem bariyerinizi koruyun."],
            ["2026 makyaj trendleri", "Makyaj", "4 dk", "Soft glam ve doğal ışıltı."],
            ["SPF kullanım rehberi", "Rehber", "5 dk", "Güneş koruyucu nasıl uygulanır?"],
            ["Hyaluronik asit nedir?", "İçerik", "3 dk", "Cildiniz için neden önemli?"],
            ["Hediye seti önerileri", "Kampanya", "4 dk", "Sevdikleriniz için ideal setler."],
            ["Müşteri yorumu: Elif S.", "Hikaye", "2 dk", "3 haftada fark edilen değişim."],
        ],
        aboutExtra: "2018'den beri güzellik kategorisinde güvenilir adresiniz. Tüm ürünler orijinal ve yetkili distribütör garantilidir.",
        cartItems: [
            ["Hyaluronik Nem Serumu × 1", "₺649"],
            ["Mat Ruj — Rose Nude × 2", "₺798"],
        ],
    },
    fashion: {
        tagline: "Sezonun en yeni parçaları",
        heroSub: "Sürdürülebilir kumaşlar, ücretsiz iade ve 24 saatte kargo.",
        promoText: "Yeni sezon — 2. üründe %30 indirim (sepette otomatik)",
        collections: [
            ["Yeni Sezon", "/collections/yeni-sezon", "2026 ilkbahar"],
            ["Elbise", "/collections/elbise", "Günlük & özel gün"],
            ["Dış Giyim", "/collections/dis-giyim", "Ceket, mont, trench"],
            ["Aksesuar", "/collections/aksesuar", "Çanta, kemer, şal"],
            ["Çok Satanlar", "/collections/cok-satan", "Haftanın favorileri"],
            ["Outlet", "/collections/outlet", "Son parçalar"],
            ["Sürdürülebilir", "/collections/surdurulebilir", "Organik pamuk"],
            ["Koleksiyon Lookbook", "/collections/lookbook", "Stil önerileri"],
        ],
        products: [
            { name: "Oversize Yün Palto", price: "₺4.990", old: "₺6.490", badge: "Yeni" },
            { name: "Saten Midi Elbise", price: "₺2.890", badge: "Çok Satan" },
            { name: "Slim Fit Chino Pantolon", price: "₺1.290", badge: "" },
            { name: "Deri Chelsea Bot", price: "₺3.490", badge: "" },
            { name: "Kaşmir Karışımlı Kazak", price: "₺1.890", old: "₺2.390", badge: "İndirim" },
            { name: "Denim Ceket — Indigo", price: "₺1.690", badge: "" },
            { name: "İpek Eşarp", price: "₺890", badge: "Premium" },
            { name: "Pileli Midi Etek", price: "₺1.190", badge: "" },
            { name: "Bomber Ceket", price: "₺2.290", badge: "Yeni" },
            { name: "Basic Organik Tişört 3'lü", price: "₺749", badge: "" },
            { name: "Deri Crossbody Çanta", price: "₺2.690", badge: "Çok Satan" },
            { name: "Yün Blazer", price: "₺3.190", badge: "" },
        ],
        blog: [
            ["İlkbahar gardırop rehberi", "Stil", "5 dk", "10 parça ile 30 kombin."],
            ["Sürdürülebilir moda nedir?", "Sürdürülebilirlik", "4 dk", "Bilinçli alışveriş ipuçları."],
            ["Lookbook: Şehir stili", "Koleksiyon", "3 dk", "Yeni sezon kombinleri."],
            ["Kumaş bakım rehberi", "Bakım", "6 dk", "Yün, ipek ve deri bakımı."],
            ["Beden rehberi", "Rehber", "2 dk", "Doğru bedeni seçin."],
            ["Outlet haftası başladı", "Kampanya", "1 dk", "%50'ye varan indirimler."],
        ],
        aboutExtra: "Türkiye'nin önde gelen online moda destinasyonlarından biri. 50.000+ mutlu müşteri, 4.8/5 mağaza puanı.",
        cartItems: [
            ["Saten Midi Elbise × 1", "₺2.890"],
            ["Deri Chelsea Bot × 1", "₺3.490"],
        ],
    },
    electronics: {
        tagline: "Resmi distribütör garantisi",
        heroSub: "Orijinal ürün, 2 yıl garanti, aynı gün kargo seçeneği.",
        promoText: "Seçili ürünlerde 12 ay taksit + ücretsiz kargo",
        collections: [
            ["Telefon & Aksesuar", "/collections/telefon", "Kılıf, şarj, kulaklık"],
            ["Bilgisayar", "/collections/bilgisayar", "Laptop, monitör, klavye"],
            ["Ses Sistemleri", "/collections/ses", "Kulaklık, hoparlör"],
            ["Akıllı Ev", "/collections/akilli-ev", "IOT, güvenlik"],
            ["Gaming", "/collections/gaming", "Konsol, aksesuar"],
            ["Kampanya", "/collections/kampanya", "Haftanın fırsatları"],
            ["Yenilenmiş", "/collections/outlet", "A kalite outlet"],
            ["Aksesuar", "/collections/aksesuar", "Kablo, stand, adaptör"],
        ],
        products: [
            { name: "Kablosuz ANC Kulaklık Pro", price: "₺3.290", old: "₺4.199", badge: "Çok Satan" },
            { name: "65W GaN Hızlı Şarj", price: "₺899", badge: "" },
            { name: "Mekanik RGB Klavye", price: "₺2.490", badge: "Yeni" },
            { name: "4K Webcam", price: "₺1.890", badge: "" },
            { name: "Taşınabilir SSD 1TB", price: "₺2.790", badge: "" },
            { name: "Akıllı Saat — Sport", price: "₺4.490", old: "₺5.290", badge: "İndirim" },
            { name: "Bluetooth Hoparlör", price: "₺1.290", badge: "" },
            { name: "USB-C Hub 7-in-1", price: "₺749", badge: "" },
            { name: "Gaming Mouse", price: "₺1.590", badge: "Gaming" },
            { name: "27\" IPS Monitör 144Hz", price: "₺8.990", badge: "Premium" },
            { name: "Robot Süpürge", price: "₺12.990", badge: "Çok Satan" },
            { name: "Akıllı Ampul 4'lü Set", price: "₺1.190", badge: "" },
        ],
        blog: [
            ["2026 en iyi kulaklık karşılaştırması", "İnceleme", "8 dk", "ANC modelleri test edildi."],
            ["Ev ofisi kurulum rehberi", "Rehber", "6 dk", "Monitör, klavye, aydınlatma."],
            ["Gaming ekipmanı seçimi", "Gaming", "5 dk", "Başlangıç seti önerileri."],
            ["Akıllı ev başlangıç paketi", "Akıllı Ev", "4 dk", "İlk adımlar."],
            ["Pil ömrünü uzatma", "İpucu", "3 dk", "Cihaz bakım önerileri."],
            ["Kargo & garanti süreçleri", "Destek", "2 dk", "Sık sorulanlar."],
        ],
        aboutExtra: "Yetkili distribütör ağı ile orijinal elektronik ürünler. Teknik destek hattı ve mağazada kurulum desteği.",
        cartItems: [
            ["Kablosuz ANC Kulaklık Pro × 1", "₺3.290"],
            ["65W GaN Hızlı Şarj × 1", "₺899"],
        ],
    },
    food: {
        tagline: "Çiftlikten sofranıza",
        heroSub: "Organik sertifikalı ürünler, soğuk zincir teslimat.",
        promoText: "İlk siparişe %15 indirim — kod: FRESH15",
        collections: [
            ["Organik Sebze", "/collections/sebze", "Günlük hasat"],
            ["Meyve", "/collections/meyve", "Mevsimlik"],
            ["Kuru Gıda", "/collections/kuru-gida", "Bakliyat, tahıl"],
            ["Şarküteri", "/collections/sarkuteri", "Peynir, zeytin"],
            ["İçecek", "/collections/icecek", "Meyve suyu, çay"],
            ["Atıştırmalık", "/collections/atistirmalik", "Sağlıklı snack"],
            ["Vegan", "/collections/vegan", "Bitki bazlı"],
            ["Haftalık Kutu", "/collections/kutu", "Abonelik paketi"],
        ],
        products: [
            { name: "Organik Zeytinyağı 500ml", price: "₺389", badge: "Çok Satan" },
            { name: "Çiğ Badem 500g", price: "₺249", badge: "" },
            { name: "Tam Buğday Ekmeği", price: "₺45", badge: "Günlük" },
            { name: "Filizlenmiş Kinoa 1kg", price: "₺199", badge: "" },
            { name: "Süt — Laktozsuz 1L", price: "₺52", badge: "" },
            { name: "Avokado 2'li Paket", price: "₺89", badge: "Yeni" },
            { name: "Organik Bal 450g", price: "₺329", old: "₺399", badge: "" },
            { name: "Granola — Yaban Mersini", price: "₺179", badge: "" },
            { name: "Cold Press Juice 6'lı", price: "₺449", badge: "" },
            { name: "Vegan Protein Bar 12'li", price: "₺299", badge: "" },
            { name: "Taze Ispanak 500g", price: "₺39", badge: "" },
            { name: "Kombucha — Ginger", price: "₺69", badge: "Yeni" },
        ],
        blog: [
            ["Organik sertifika nedir?", "Bilgi", "4 dk", "Etiketleri nasıl okursunuz?"],
            ["Haftalık meal prep", "Tarif", "7 dk", "5 günlük sağlıklı plan."],
            ["Soğuk zincir teslimat", "Lojistik", "3 dk", "Tazelik garantimiz."],
            ["Vegan beslenme başlangıç", "Rehber", "5 dk", "Temel ürün listesi."],
            ["Mevsim takvimi", "Rehber", "4 dk", "Hangi ay hangi ürün?"],
            ["Yeni çiftlik ortaklığı", "Haber", "2 dk", "Ege bölgesi üreticileri."],
        ],
        aboutExtra: "Yerel üreticilerle doğrudan çalışıyoruz. Ürünlerin %78'i Türkiye içi organik sertifikalı kaynaklardan gelir.",
        cartItems: [
            ["Organik Zeytinyağı × 2", "₺778"],
            ["Avokado 2'li Paket × 3", "₺267"],
        ],
    },
    furniture: {
        tagline: "Eviniz için tasarlandı",
        heroSub: "Ücretsiz kurulum, 2 yıl garanti, 30 gün iade.",
        promoText: "Salon koleksiyonunda %25 indirim — sınırlı stok",
        collections: [
            ["Oturma Odası", "/collections/oturma", "Kanepe, sehpa"],
            ["Yatak Odası", "/collections/yatak", "Karyola, gardırop"],
            ["Yemek Odası", "/collections/yemek", "Masa, sandalye"],
            ["Ofis", "/collections/ofis", "Masa, ergonomik sandalye"],
            ["Aydınlatma", "/collections/aydinlatma", "Lambader, avize"],
            ["Dekor", "/collections/dekor", "Halı, vazo, tablo"],
            ["Bahçe", "/collections/bahce", "Outdoor mobilya"],
            ["Outlet", "/collections/outlet", "Son parçalar"],
        ],
        products: [
            { name: "3'lü Kumaş Kanepe — Bej", price: "₺24.990", old: "₺32.990", badge: "Çok Satan" },
            { name: "Masif Meşe Yemek Masası", price: "₺18.900", badge: "" },
            { name: "Ergonomik Ofis Sandalyesi", price: "₺6.490", badge: "Yeni" },
            { name: "Minimal TV Ünitesi", price: "₺4.290", badge: "" },
            { name: "Queen Yatak Baza Set", price: "₺14.990", badge: "" },
            { name: "Berjer — Kadife Yeşil", price: "₺7.890", badge: "" },
            { name: "Kitaplık — 5 Raflı", price: "₺3.490", badge: "" },
            { name: "Yün Halı 160×230", price: "₺2.890", badge: "İndirim" },
            { name: "LED Lambader", price: "₺1.290", badge: "" },
            { name: "6'lı Yemek Sandalyesi", price: "₺9.990", badge: "" },
            { name: "Çalışma Masası 140cm", price: "₺5.490", badge: "" },
            { name: "Balkon Seti 3+1", price: "₺8.990", badge: "Yaz" },
        ],
        blog: [
            ["Küçük salon dekorasyonu", "İlham", "6 dk", "Metrekareyi büyütün."],
            ["Ahşap bakım rehberi", "Bakım", "4 dk", "Masif mobilya ömrü."],
            ["2026 renk paletleri", "Trend", "3 dk", "Toprak tonları öne çıkıyor."],
            ["Ev ofisi kurulumu", "Rehber", "5 dk", "Verimli çalışma alanı."],
            ["Teslimat & kurulum", "Destek", "3 dk", "Süreç nasıl işler?"],
            ["Müşteri evi: İstanbul", "Hikaye", "4 dk", "Dönüşüm öncesi/sonrası."],
        ],
        aboutExtra: "15 yıllık mobilya üretim tecrübesi. Montaj ekibimiz 81 ilde hizmet verir.",
        cartItems: [
            ["Minimal TV Ünitesi × 1", "₺4.290"],
            ["LED Lambader × 2", "₺2.580"],
        ],
    },
    kids: {
        tagline: "Minikler için güvenli & eğlenceli",
        heroSub: "CE sertifikalı oyuncaklar, organik kıyafetler, hızlı teslimat.",
        promoText: "Okul sezonu — 3. üründe %50 indirim",
        collections: [
            ["Oyuncak", "/collections/oyuncak", "0–12 yaş"],
            ["Giyim", "/collections/giyim", "Bebek & çocuk"],
            ["Ayakkabı", "/collections/ayakkabi", "Okul & spor"],
            ["Bebek", "/collections/bebek", "0–24 ay"],
            ["Okul", "/collections/okul", "Çanta, kırtasiye"],
            ["Outdoor", "/collections/outdoor", "Park & bahçe"],
            ["Yeni Sezon", "/collections/yeni", "2026 koleksiyon"],
            ["Hediye", "/collections/hediye", "Doğum günü setleri"],
        ],
        products: [
            { name: "Ahşap Blok Seti 50 Parça", price: "₺449", badge: "Çok Satan" },
            { name: "Organik Pamuk Body 3'lü", price: "₺299", badge: "" },
            { name: "LED Gece Lambası — Ay", price: "₺189", badge: "Yeni" },
            { name: "Okul Çantası — Unicorn", price: "₺549", badge: "" },
            { name: "Eğitici Puzzle 100 Parça", price: "₺159", badge: "" },
            { name: "Çocuk Sneaker — Mavi", price: "₺690", old: "₺890", badge: "İndirim" },
            { name: "Bebek Battaniyesi — Organik", price: "₺379", badge: "" },
            { name: "Scooter 3 Teker", price: "₺1.290", badge: "" },
            { name: "Boyama Seti Deluxe", price: "₺129", badge: "" },
            { name: "Peluş Ayı 40cm", price: "₺249", badge: "Hediye" },
            { name: "Yağmurluk — Sarı", price: "₺319", badge: "" },
            { name: "Müzikli Mobil", price: "₺459", badge: "Yeni" },
        ],
        blog: [
            ["Okula dönüş alışveriş listesi", "Rehber", "5 dk", "Temel ihtiyaçlar checklist."],
            ["Oyuncak güvenliği", "Güvenlik", "4 dk", "CE işareti nedir?"],
            ["0–2 yaş giyim rehberi", "Giyim", "3 dk", "Beden tablosu."],
            ["Eğitici oyuncak seçimi", "Rehber", "6 dk", "Yaşa uygun öneriler."],
            ["Organik bebek tekstili", "Sürdürülebilirlik", "4 dk", "Neden önemli?"],
            ["Müşteri hikayesi: Can'ın annesi", "Hikaye", "2 dk", "Okul çantası deneyimi."],
        ],
        aboutExtra: "2015'ten beri ebeveynlerin güvendiği çocuk ürünleri mağazası. Tüm oyuncaklar yaş grubuna uygun sertifikalıdır.",
        cartItems: [["Ahşap Blok Seti × 1", "₺449"], ["Okul Çantası × 1", "₺549"]],
    },
    pet: {
        tagline: "Dostlarınız için en iyisi",
        heroSub: "Premium mama, aksesuar ve bakım ürünleri — veteriner onaylı markalar.",
        promoText: "Mama aboneliğinde %10 indirim + ücretsiz kargo",
        collections: [
            ["Köpek", "/collections/kopek", "Mama, tasma, yatak"],
            ["Kedi", "/collections/kedi", "Kum, oyuncak, tırmalama"],
            ["Kuş", "/collections/kus", "Yem, kafes"],
            ["Balık", "/collections/balik", "Akvaryum malzemeleri"],
            ["Bakım", "/collections/bakim", "Şampuan, tırnak"],
            ["Oyuncak", "/collections/oyuncak", "Eğlence & aktivite"],
            ["Sağlık", "/collections/saglik", "Vitamin, supplement"],
            ["Yeni", "/collections/yeni", "Bu ayın ürünleri"],
        ],
        products: [
            { name: "Premium Köpek Maması 15kg", price: "₺1.890", badge: "Çok Satan" },
            { name: "Kedi Kumu — Kokusuz 10L", price: "₺249", badge: "" },
            { name: "Ortopedik Pet Yatağı L", price: "₺890", badge: "Yeni" },
            { name: "Tırmalama Tahtası", price: "₺459", badge: "" },
            { name: "Otomatik Su Kabı", price: "₺329", badge: "" },
            { name: "Köpek Tasması — Deri", price: "₺399", old: "₺499", badge: "" },
            { name: "İnteraktif Kedi Oyuncağı", price: "₺189", badge: "" },
            { name: "Tüy Tarağı Seti", price: "₺149", badge: "" },
            { name: "Köpek Ödül Maması 500g", price: "₺119", badge: "" },
            { name: "Taşıma Çantası — Medium", price: "₺690", badge: "" },
            { name: "Akvaryum Filtresi", price: "₺549", badge: "" },
            { name: "Pet Şampuanı 500ml", price: "₺179", badge: "" },
        ],
        blog: [
            ["Köpek maması seçim rehberi", "Rehber", "6 dk", "Yaş ve ırka göre öneriler."],
            ["Kedi kumu türleri", "Rehber", "4 dk", "Bentonit vs silika."],
            ["Evcil hayan sağlığı", "Sağlık", "5 dk", "Aşı takvimi hatırlatıcı."],
            ["Yaz bakım ipuçları", "Bakım", "3 dk", "Sıcak havalarda dikkat."],
            ["Yeni mama markası", "Haber", "2 dk", "Premium seri lansmanı."],
        ],
        aboutExtra: "Evcil hayvan sahiplerinin güvendiği online pet shop. 200+ marka, aynı gün kargo seçeneği.",
        cartItems: [["Premium Köpek Maması × 1", "₺1.890"], ["Köpek Tasması × 1", "₺399"]],
    },
    sports: {
        tagline: "Performans için tasarlandı",
        heroSub: "Profesyonel ekipman, orijinal marka garantisi, fitness rehberleri.",
        promoText: "Sezon sonu — seçili ürünlerde %40 indirim",
        collections: [
            ["Fitness", "/collections/fitness", "Ağırlık, mat, band"],
            ["Koşu", "/collections/kosu", "Ayakkabı, kıyafet"],
            ["Outdoor", "/collections/outdoor", "Kamp, trekking"],
            ["Takım Sporları", "/collections/takim", "Futbol, basketbol"],
            ["Yüzme", "/collections/yuzme", "Mayo, gözlük"],
            ["Bisiklet", "/collections/bisiklet", "Aksesuar, kask"],
            ["Erkek", "/collections/erkek", "Erkek koleksiyonu"],
            ["Kadın", "/collections/kadin", "Kadın koleksiyonu"],
        ],
        products: [
            { name: "Koşu Ayakkabısı — Pro", price: "₺3.490", old: "₺4.290", badge: "Çok Satan" },
            { name: "Yoga Matı 6mm", price: "₺449", badge: "" },
            { name: "Dumbbell Set 2×10kg", price: "₺1.890", badge: "" },
            { name: "Performans Tişört", price: "₺399", badge: "Yeni" },
            { name: "Su Şişesi 750ml — Pro", price: "₺249", badge: "" },
            { name: "Futbol Topu — FIFA Onaylı", price: "₺590", badge: "" },
            { name: "Trekking Bot", price: "₺2.890", badge: "" },
            { name: "Fitness Eldiveni", price: "₺199", badge: "" },
            { name: "Bisiklet Kaskı", price: "₺690", badge: "Güvenlik" },
            { name: "Resistance Band Set", price: "₺279", badge: "" },
            { name: "Yüzme Gözlüğü", price: "₺329", badge: "" },
            { name: "Spor Çantası 45L", price: "₺890", badge: "" },
        ],
        blog: [
            ["Maraton hazırlık planı", "Koşu", "8 dk", "12 haftalık program."],
            ["Evde fitness ekipmanı", "Fitness", "5 dk", "Başlangıç seti."],
            ["Doğru koşu ayakkabısı", "Rehber", "4 dk", "Pronasyon rehberi."],
            ["Outdoor kamp checklist", "Outdoor", "6 dk", "Temel ekipman listesi."],
            ["Protein ve beslenme", "Beslenme", "5 dk", "Sporcu diyeti ipuçları."],
            ["Yeni sezon koleksiyonu", "Kampanya", "2 dk", "İndirimler başladı."],
        ],
        aboutExtra: "Spor tutkunları için orijinal ekipman. 15.000+ ürün, mağazada deneme imkânı (seçili şehirler).",
        cartItems: [["Koşu Ayakkabısı × 1", "₺3.490"], ["Performans Tişört × 2", "₺798"]],
    },
    general: {
        tagline: "Premium e-ticaret deneyimi",
        heroSub: "Binlerce ürün, hızlı kargo ve güvenli ödeme ile alışverişe başlayın.",
        promoText: "500 ₺ üzeri siparişlerde ücretsiz kargo — bugün sipariş verin!",
        collections: [
            ["Yeni Gelenler", "/collections/yeni", "Bu haftanın ürünleri"],
            ["Çok Satanlar", "/collections/cok-satan", "Müşteri favorileri"],
            ["İndirim", "/collections/indirim", "Kampanyalı ürünler"],
            ["Premium", "/collections/premium", "Seçkin koleksiyon"],
            ["Hediye", "/collections/hediye", "Hediye fikirleri"],
            ["Aksesuar", "/collections/aksesuar", "Tamamlayıcı ürünler"],
            ["Outlet", "/collections/outlet", "Son fırsatlar"],
            ["Koleksiyonlar", "/collections", "Tüm kategoriler"],
        ],
        products: [
            { name: "Premium Hoodie", price: "₺1.299", old: "₺1.599", badge: "Çok Satan" },
            { name: "Minimal Sneaker", price: "₺2.490", badge: "Yeni" },
            { name: "Canvas Tote Çanta", price: "₺890", badge: "" },
            { name: "Wireless Earbuds Pro", price: "₺3.290", badge: "" },
            { name: "Classic Watch", price: "₺4.750", badge: "Premium" },
            { name: "Organic Serum 30ml", price: "₺649", badge: "" },
            { name: "Smart LED Lamba", price: "₺1.890", badge: "" },
            { name: "Travel Backpack 40L", price: "₺2.190", badge: "" },
            { name: "Sport Performance Tişört", price: "₺449", badge: "" },
            { name: "Denim Jacket", price: "₺1.590", old: "₺1.990", badge: "İndirim" },
            { name: "Deri Kemer", price: "₺699", badge: "" },
            { name: "İpek Şal", price: "₺899", badge: "" },
        ],
        blog: [
            ["2026 alışveriş trendleri", "Trend", "5 dk", "Online perakende raporu."],
            ["Sürdürülebilir paketleme", "Sürdürülebilirlik", "4 dk", "Çevre dostu kargo."],
            ["Yeni sezon koleksiyonu", "Koleksiyon", "3 dk", "Lookbook yayında."],
            ["Müşteri hikayesi", "Hikaye", "6 dk", "Ayşe'nin deneyimi."],
            ["Kargo ve iade süreçleri", "Destek", "4 dk", "Adım adım rehber."],
            ["Kampanya: %30 indirim", "Kampanya", "2 dk", "Seçili ürünlerde."],
        ],
        aboutExtra: "Güvenilir online alışveriş için doğru adres. 100.000+ sipariş, 4.9/5 müşteri memnuniyeti.",
        cartItems: [["Premium Hoodie × 1", "₺1.299"], ["Minimal Sneaker × 1", "₺2.490"]],
    },
    jewelry: {
        tagline: "Zarif mücevher koleksiyonu",
        heroSub: "Sertifikalı taşlar, özel tasarım ve hediye paketleme — aynı gün kargo.",
        promoText: "Sevgililer Günü — pırlanta koleksiyonunda %20 indirim",
        collections: [
            ["Yüzük", "/collections/yuzuk", "Tektaş & alyans"],
            ["Kolye", "/collections/kolye", "Altın & gümüş"],
            ["Küpe", "/collections/kupe", "Günlük & özel gün"],
            ["Bileklik", "/collections/bileklik", "Zincir & charm"],
            ["Pırlanta", "/collections/pirlanta", "Sertifikalı taşlar"],
            ["Erkek", "/collections/erkek", "Kol saati & aksesuar"],
            ["Hediye", "/collections/hediye", "Özel gün setleri"],
            ["Yeni", "/collections/yeni", "Bu ayın tasarımları"],
        ],
        products: [
            { name: "Tektaş Pırlanta Yüzük 0.35ct", price: "₺24.900", badge: "Premium" },
            { name: "14 Ayar Altın Halka Küpe", price: "₺3.490", badge: "Çok Satan" },
            { name: "İnci Kolye — Tek Sıra", price: "₺2.890", badge: "" },
            { name: "Zincir Bileklik — Rose Gold", price: "₺1.790", badge: "Yeni" },
            { name: "Alyans Çifti — Mat Altın", price: "₺8.900", badge: "" },
            { name: "Safir Taşlı Yüzük", price: "₺12.500", old: "₺14.900", badge: "İndirim" },
            { name: "Minimal Gümüş Kolye", price: "₺890", badge: "" },
            { name: "Charm Bileklik Seti", price: "₺2.290", badge: "" },
            { name: "Elmas Detaylı Küpe", price: "₺6.750", badge: "Premium" },
            { name: "Erkek Deri Bileklik", price: "₺1.290", badge: "" },
            { name: "Kalp Kolye — 18 Ayar", price: "₺4.190", badge: "Hediye" },
            { name: "Vintage Yüzük Koleksiyonu", price: "₺3.690", badge: "" },
        ],
        blog: [
            ["Yüzük bedeni nasıl ölçülür?", "Rehber", "3 dk", "Evde doğru ölçüm yöntemi."],
            ["Pırlanta 4C rehberi", "Bilgi", "6 dk", "Kesim, renk, berraklık, karat."],
            ["Mücevher bakım ipuçları", "Bakım", "4 dk", "Parlatma ve saklama."],
            ["Alyans seçim rehberi", "Rehber", "5 dk", "Çiftler için öneriler."],
            ["Hediye paketleme", "Hizmet", "2 dk", "Özel gün sunumları."],
            ["Yeni koleksiyon lansmanı", "Haber", "2 dk", "İlkbahar 2026 parçaları."],
        ],
        aboutExtra: "1998'den beri sertifikalı mücevher ve altın ürünler. Her parça GIA/HRD sertifikalı taşlarla sunulur.",
        cartItems: [["Tektaş Pırlanta Yüzük × 1", "₺24.900"], ["14 Ayar Altın Halka Küpe × 1", "₺3.490"]],
    },
    luxury: {
        tagline: "Zamansız lüks deneyim",
        heroSub: "Seçkin parçalar, kişisel stilist desteği ve VIP teslimat.",
        promoText: "Private Sale — seçili parçalarda davetiye ile %25 indirim",
        collections: [
            ["Haute Couture", "/collections/couture", "Özel dikim"],
            ["Aksesuar", "/collections/aksesuar", "Çanta & kemer"],
            ["Ayakkabı", "/collections/ayakkabi", "Deri & süet"],
            ["Outerwear", "/collections/dis-giyim", "Palto & ceket"],
            ["Limited Edition", "/collections/limited", "Sınırlı üretim"],
            ["Erkek", "/collections/erkek", "Premium erkek"],
            ["Kadın", "/collections/kadin", "Premium kadın"],
            ["Archive", "/collections/archive", "Sezon arşivi"],
        ],
        products: [
            { name: "İtalyan Deri Tote — Siyah", price: "₺18.900", badge: "Limited" },
            { name: "Kaşmir Palto — Camel", price: "₺32.500", badge: "Premium" },
            { name: "İpek Gecelik Seti", price: "₺6.900", badge: "" },
            { name: "El Dikişi Oxford Ayakkabı", price: "₺9.800", badge: "Çok Satan" },
            { name: "Altın Kaplama Kol Saati", price: "₺42.000", badge: "Exclusive" },
            { name: "Yün Blazer — Lacivert", price: "₺14.500", badge: "" },
            { name: "İpek Eşarp — Monogram", price: "₺3.900", badge: "" },
            { name: "Deri Kartlık", price: "₺2.490", badge: "Hediye" },
            { name: "Satén Akşam Elbisesi", price: "₺22.900", old: "₺28.900", badge: "Private Sale" },
            { name: "Kasmir Kazak — Gri", price: "₺8.900", badge: "" },
            { name: "Signature Parfüm 100ml", price: "₺5.600", badge: "Yeni" },
            { name: "Deri Kemer — Antik Toka", price: "₺3.290", badge: "" },
        ],
        blog: [
            ["Lüks alışveriş rehberi", "Stil", "5 dk", "Kalıcı parça seçimi."],
            ["Kaşmir bakımı", "Bakım", "4 dk", "Uzun ömürlü kullanım."],
            ["Private Sale davetiyesi", "Kampanya", "2 dk", "VIP müşteri ayrıcalıkları."],
            ["Sezon lookbook", "Koleksiyon", "6 dk", "2026 ilkbahar."],
            ["Kişisel stilist hizmeti", "Hizmet", "3 dk", "Randevu nasıl alınır?"],
            ["Sürdürülebilir lüks", "Değerler", "4 dk", "Etik tedarik zinciri."],
        ],
        aboutExtra: "Dünya çapında seçkin markaların resmi partneri. VIP teslimat ve kişisel alışveriş danışmanlığı.",
        cartItems: [["İtalyan Deri Tote × 1", "₺18.900"], ["Kaşmir Palto × 1", "₺32.500"]],
    },
    digital: {
        tagline: "Dijital ürünler & SaaS",
        heroSub: "Anında teslimat, lisans anahtarı e-postada — kurumsal faturalandırma mevcut.",
        promoText: "Yıllık planlarda 2 ay bedava — kod: DIGITAL2026",
        collections: [
            ["Yazılım", "/collections/yazilim", "Lisans & abonelik"],
            ["E-kitap", "/collections/e-kitap", "PDF & EPUB"],
            ["Kurs", "/collections/kurs", "Video eğitim"],
            ["Şablon", "/collections/sablon", "UI kit & tema"],
            ["Müzik", "/collections/muzik", "Beat & sample"],
            ["Grafik", "/collections/grafik", "Stok & vektör"],
            ["Oyun", "/collections/oyun", "Dijital key"],
            ["Kurumsal", "/collections/kurumsal", "Toplu lisans"],
        ],
        products: [
            { name: "Pro Tasarım Suite — Yıllık", price: "₺2.990", badge: "Çok Satan" },
            { name: "E-Ticaret Starter Kit", price: "₺1.490", badge: "Yeni" },
            { name: "SEO Masterclass Kursu", price: "₺890", badge: "" },
            { name: "UI Component Pack 500+", price: "₺749", badge: "" },
            { name: "SaaS Landing Template", price: "₺449", badge: "" },
            { name: "Stock Photo Bundle 10K", price: "₺1.290", badge: "İndirim" },
            { name: "Python Automation E-kitap", price: "₺199", badge: "" },
            { name: "Notion İş Şablonları", price: "₺149", badge: "" },
            { name: "Video Edit Preset Pack", price: "₺329", badge: "" },
            { name: "Kurumsal API Lisansı", price: "₺9.900", badge: "Kurumsal" },
            { name: "Mobil App UI Kit", price: "₺599", badge: "Yeni" },
            { name: "Podcast Intro Müzik Paketi", price: "₺249", badge: "" },
        ],
        blog: [
            ["Dijital ürün satış rehberi", "Rehber", "7 dk", "Lisans yönetimi ve teslimat."],
            ["SaaS fiyatlandırma", "İş", "5 dk", "Abonelik modelleri."],
            ["Anında teslimat altyapısı", "Teknik", "4 dk", "Otomasyon ipuçları."],
            ["Kurumsal lisanslama", "Kurumsal", "3 dk", "Toplu satın alma."],
            ["Yeni şablon paketi", "Lansman", "2 dk", "500+ bileşen eklendi."],
            ["Müşteri başarı hikayesi", "Hikaye", "4 dk", "Aylık 50K+ indirme."],
        ],
        aboutExtra: "Dijital ürün satıcıları için güvenilir platform. Anında teslimat, otomatik lisans ve 7/24 teknik destek.",
        cartItems: [["Pro Tasarım Suite × 1", "₺2.990"], ["SEO Masterclass × 1", "₺890"]],
    },
    marketplace: {
        tagline: "Binlerce satıcı, milyonlarca ürün",
        heroSub: "Güvenli alışveriş koruması, hızlı iade ve çoklu satıcı sepeti.",
        promoText: "Yeni üyelere ilk siparişte 100 ₺ indirim kuponu",
        collections: [
            ["Elektronik", "/collections/elektronik", "12.000+ ürün"],
            ["Moda", "/collections/moda", "45.000+ ürün"],
            ["Ev & Yaşam", "/collections/ev", "28.000+ ürün"],
            ["Kozmetik", "/collections/kozmetik", "8.500+ ürün"],
            ["Spor", "/collections/spor", "15.000+ ürün"],
            ["Kitap & Hobi", "/collections/kitap", "20.000+ ürün"],
            ["Süpermarket", "/collections/market", "Günlük ihtiyaç"],
            ["Outlet", "/collections/outlet", "Fırsat ürünleri"],
        ],
        products: [
            { name: "Kablosuz Kulaklık — Satıcı A", price: "₺899", old: "₺1.299", badge: "Fırsat" },
            { name: "Organik Zeytinyağı 1L", price: "₺289", badge: "Çok Satan" },
            { name: "Oversize Hoodie — Satıcı B", price: "₺449", badge: "" },
            { name: "Robot Süpürge Pro", price: "₺8.990", badge: "Premium" },
            { name: "Çocuk Oyuncak Seti", price: "₺199", badge: "" },
            { name: "Akıllı Saat Sport", price: "₺2.490", badge: "Yeni" },
            { name: "Masa Lambası LED", price: "₺349", badge: "" },
            { name: "Protein Tozu 2kg", price: "₺790", badge: "" },
            { name: "Deri Cüzdan", price: "₺259", badge: "" },
            { name: "Bluetooth Hoparlör", price: "₺599", old: "₺799", badge: "İndirim" },
            { name: "Kahve Makinesi", price: "₺3.290", badge: "" },
            { name: "Yoga Matı Set", price: "₺329", badge: "" },
        ],
        blog: [
            ["Pazar yeri güvenli alışveriş", "Güven", "4 dk", "Alıcı koruma programı."],
            ["Satıcı olmak", "Satıcı", "6 dk", "Mağaza açma rehberi."],
            ["Çoklu satıcı sepeti", "Rehber", "3 dk", "Tek ödemede birleşik sipariş."],
            ["Haftanın fırsatları", "Kampanya", "2 dk", "Seçili kategorilerde indirim."],
            ["Kargo birleştirme", "Lojistik", "3 dk", "Aynı gün gönderim ipuçları."],
            ["Müşteri yorumları", "Topluluk", "5 dk", "En yüksek puanlı satıcılar."],
        ],
        aboutExtra: "Türkiye'nin büyüyen çok satıcılı pazar yeri. 5.000+ aktif satıcı, güvenli ödeme altyapısı.",
        cartItems: [["Kablosuz Kulaklık × 1", "₺899"], ["Organik Zeytinyağı × 2", "₺578"]],
    },
};

const SLUG_VERTICAL = {
    "modern-store": "general",
    "dawn-trade": "digital",
    "fashion-pro": "fashion",
    "craft-boutique": "fashion",
    "spotlight-showcase": "fashion",
    "electronics-plus": "electronics",
    "minimal-luxury": "luxury",
    "beauty-store": "beauty",
    "food-store": "food",
    "furniture-store": "furniture",
    "lumiere-fashion": "fashion",
    "luxury-brand": "luxury",
    "jewelry-store": "jewelry",
    "kids-store": "kids",
    "pet-store": "pet",
    "sports-store": "sports",
    "home-decor": "furniture",
    "digital-products": "digital",
    "marketplace-pro": "marketplace",
    "vercel-commerce": "digital",
    "medusa-starter": "general",
    "saleor-storefront": "general",
    "shadcn-storefront": "luxury",
    "tailwind-blocks": "general",
    "commerce-daisy": "general",
    "bootstrap-store": "general",
    "storefront-minimal": "luxury",
    "boutique-elegant": "fashion",
    "dark-commerce": "electronics",
};

function resolveVertical(cfg = {}) {
    if (cfg.vertical && VERTICALS[cfg.vertical]) return cfg.vertical;
    if (cfg.slug && SLUG_VERTICAL[cfg.slug]) return SLUG_VERTICAL[cfg.slug];
    const cat = String(cfg.category || "").toLowerCase();
    if (cat.includes("güzellik") || cat.includes("kozmetik")) return "beauty";
    if (cat.includes("moda") || cat.includes("butik") || cat.includes("mücevher") || cat.includes("lüks")) {
        if (cat.includes("mücevher")) return "jewelry";
        if (cat.includes("lüks")) return "luxury";
        return "fashion";
    }
    if (cat.includes("elektronik")) return "electronics";
    if (cat.includes("dijital")) return "digital";
    if (cat.includes("pazar")) return "marketplace";
    if (cat.includes("gıda")) return "food";
    if (cat.includes("mobilya") || cat.includes("dekor")) return "furniture";
    if (cat.includes("çocuk")) return "kids";
    if (cat.includes("pet")) return "pet";
    if (cat.includes("spor")) return "sports";
    return "general";
}

function getVertical(cfg) {
    const key = resolveVertical(cfg);
    return VERTICALS[key] || VERTICALS.general;
}

function mergeCfg(cfg) {
    const vKey = resolveVertical(cfg);
    const v = getVertical(cfg);
    return {
        ...cfg,
        tagline: cfg.tagline || v.tagline,
        heroSub: cfg.heroSub || v.heroSub,
        promoText: cfg.promoText || v.promoText,
        aboutExtra: cfg.aboutExtra || v.aboutExtra,
        _vertical: v,
        _verticalKey: vKey,
        _assets: getThemeAssets(vKey),
    };
}

module.exports = {
    VERTICALS,
    resolveVertical,
    getVertical,
    mergeCfg,
};
